### ISSUE TITLE
Multiple circles in one line

### ISSUE THREAD

**Issue by ankitgohel1996** [kottenator/jquery-circle-progress#100]
How do I render more than one circle in one line? For some reason the circle element takes up 100% of the width, even after setting the width manually to 100px by 100px. <br>
![screenshot 285](https://cloud.githubusercontent.com/assets/13375914/16531260/4d102346-3fe9-11e6-80c5-c6d8c686f653.png)

```
#circle1,#circle2
{
	height:100px;
	width:100px;
}

<div id="circle1"> </div>

<div id="circle2"> </div>

```

I've attached a picture to show what I mean.

**Comment by ankitgohel1996** [comment]
I got the problem, thanks anyway!

**Comment by kottenator** [comment]
Sorry, I was on vacation. I'm glad that you've solved the problem by yourself ;)
