### ISSUE TITLE
Multiple circles with numeric values inside

### ISSUE THREAD

**Issue by ankitgohel1996** [kottenator/jquery-circle-progress#101]
I looked through the snippet you provided for #98, but the problem is when there are multiple circles, the numeric value inside each circle is not displayed correctly. The value inside each circle is the data value of the last circle drawn

The JS bin from #98 : http://jsbin.com/tegama/2/edit?html,css,js,output

Thus is what it looks like:
![screenshot 286](https://cloud.githubusercontent.com/assets/13375914/16534492/c022e454-3ffd-11e6-958a-a83b98a2422f.png)

Do you know how I can fix this?

**Comment by kottenator** [comment]
The problem is in your JS: `value = circle.children('.value')` - this means that both circles will update each others values at the same time. [Here is your example with fixed JS](http://jsbin.com/zonizofuwo/1/edit?js,output).
