### ISSUE TITLE
Drawing a Hexagon

### ISSUE THREAD

**Issue by swillis93** [kottenator/jquery-circle-progress#102]
Hi I've been trying to adapt your triangle example into a hexagon but I don't understand the code enough for the fill. 

I've used the following for the empty shape;

```
        ctx.moveTo(50, 1);
        ctx.lineTo(99, 37);
        ctx.lineTo(80, 96);
        ctx.lineTo(20, 96);
        ctx.lineTo(1, 37);
```

Could you please give me a hand getting the fill to follow this shape too?

Thanks, really appreciate your work on this script

**Comment by kottenator** [comment]
Hi, @swillis93! I'll gladly help you, I'm just super busy at work last 2 weeks.

**Comment by swillis93** [comment]
Great, thank you

**Comment by kottenator** [comment]
[Finally, here it is](http://jsbin.com/puvoxi/3/edit?js,output).

**Comment by swillis93** [comment]
Fantastic thank you so much
