### ISSUE TITLE
before and after circle  #help

### ISSUE THREAD

**Issue by MohammadMahmoud** [kottenator/jquery-circle-progress#103]
![diagram](https://cloud.githubusercontent.com/assets/17513805/17277110/79921cbc-573b-11e6-9df9-ae503aac3d5d.png)

how i could make those small circles 

thanks a lot

**Comment by kottenator** [comment]
Please, take a look at #21, it should help.

**Comment by MohammadMahmoud** [comment]
Thanks alot

**Comment by kottenator** [comment]
To make it easier, here is [a snippet for your case](http://jsbin.com/misavo/2/edit?html,js,output).

**Comment by MohammadMahmoud** [comment]
i'm very very thank full sir..wish you have nice day :+1:  :+1:  :)

**Comment by kottenator** [comment]
You're very welcome! ;)

**Comment by swillis93** [comment]
How would I go about getting the after dot to work when the arc is reversed, going anti clockwise rather than clockwise?

Thanks

**Comment by paritosharya408** [comment]
Hi @kottenator 
 Just what I was looking for. Is it possible to add the progressbar text/values inside the end circle? This is what i am looking for.

![capture](https://user-images.githubusercontent.com/13437505/29392165-bbb7b0a6-8319-11e7-8dec-c79adb4b8238.PNG)
