### ISSUE TITLE
popup circle, take up load

### ISSUE THREAD

**Issue by oharryo** [kottenator/jquery-circle-progress#104]
Hello Friend,

I need a help, would be able to resume the time charging, in order that only lasts one minute the total load.

I can not hide and mostar with the process down , because the tags are cleaned , so it should resume the process at any time, popup close not only to click on specific location.

In the example is 75 % for the missing 45 seconds to complete 

![image](https://cloud.githubusercontent.com/assets/3268758/17371035/0a02c54c-5964-11e6-9bd4-3a465f4ff77d.png)

https://jsbin.com/mahanel/edit?js,console,output

**Comment by kottenator** [comment]
Pardon me but I don't understand the problem. Could you provide an algorithm?

**Comment by oharryo** [comment]
I wish that when the circle process is done , at the time it closes , when you reopen the circle process to recover the missing amount.
1. click **button strat** open PopUp.
2. load regressive process time.
3. by waiting 15 seconds, the regressive process should be in the 75 %
4. click **button close PopUP**
5. eliminate circle process
6. close window popup.
7. wait 30 seconds.
8. click **button continue** open PopUp.
9. the process should continue from 25%, and this should continue to fall until it reaches 0%.
10. when finished 15 seconds missing , you close the popup.

**Comment by jacobnbrum** [comment]
This should be closer to what you want. 

[JsBin](https://jsbin.com/nifecuquvi/edit?js,console,output
)
You need to set the `animationStartValue`. You can get the current value from the `stepValue`.

**Comment by kottenator** [comment]
@oharryo: [here is a snippet for you](https://jsbin.com/lemife/3/edit?html,js,output). I hope that's what you wanted, I'm still not 100% sure :)

**Comment by kottenator** [comment]
It's been a week since my last comment. I hope my snippet has helped you. I'm closing this ticket.
