### ISSUE TITLE
Animate on hover

### ISSUE THREAD

**Issue by caseydev** [kottenator/jquery-circle-progress#105]
hi, can i make this progress bar animate on hover. Now its load after page load. I am expecting on hover. Please help me guys.

**Comment by kottenator** [comment]
Please, take a look at #78

**Comment by caseydev** [comment]
Thanks a lot for quick response. Its almost done actually i want like this after mouseout it will not filled like this. Now i have done
http://codepen.io/caseydev/pen/OXBPLb

Anyway thanks again

**Comment by kottenator** [comment]
I hope you've handled your problem. I'm closing this ticket.
