### ISSUE TITLE
Support multiple (separate) values

### ISSUE THREAD

**Issue by ryanrishi** [kottenator/jquery-circle-progress#106]
This library is great for showing the progress of something that is loading or playing. Is there a way to show both load progress _and_ play progress, ie. have supporting multiple values?

For example, if I'm loading audio via html, I can start playing before the entire audio file has loaded. It would be great to show load progress as it continues to load and also animate the circle as it plays.

This is more of a feature request than a bug.

**Comment by kottenator** [comment]
Hi!

I see that you did a big job with your pull-request, it looks really high-quality and professional... 

However, I'm not sure that this functionality belongs to the _library core_. It looks very custom, not everybody will need/use it. 

I'm trying to avoid overwhelming the _library core_. But you may use your fork as a customization for your needs, if you want to.

Actually, I was going to advise you to not modify the library but rather to create 2 circles, one over another - so you'll have what you need without any code modifications. [Here is a snippet](http://jsbin.com/puvoxi/2/edit?html,css,js,output) of how it can be done.

**Comment by ryanrishi** [comment]
Hey, thanks for the feedback and snippet! You're right, this doesn't belong in the library core. Are there any plans to make this project more modular?

**Comment by kottenator** [comment]
Yes, I have this idea for a long time. And I'd appreciate if you wish to participate in its implementation ;)

**Comment by kottenator** [comment]
I've created a ticket to implement plugin-compatible architecture - #111.

I'm going to close this ticket. I really believe that it's better to create 2 separate circles, but it's up to you.

And I'm going to reject your PR, sorry about that.
