### ISSUE TITLE
Padding at bottom, not fully circular?

### ISSUE THREAD

**Issue by ectoraige** [kottenator/jquery-circle-progress#107]
I'm trying to use it inline with some text but was having difficulty with vertical positioning. Further investigation shows that the circle is not filling the square, perhaps the bottom arc is not centered correctly?

Example at [JSFiddle](https://jsfiddle.net/ectoraige/zcsno0uz/)

I've tried various values for size and width, happens with both even and odd values.

**Comment by kottenator** [comment]
It's the same problem that you have with `<img>` - it has some undefined _bottom margin_ which can be removed by specifying (e.g.) `vertical-align: top`.

Here is [an example with middle-aligned inline circle](http://jsbin.com/dovelu/edit?html,css,js,output).

**Comment by kottenator** [comment]
I believe this problem is solved.

**Comment by ectoraige** [comment]
Indeed that fixed it, thank you, excellent library.
