### ISSUE TITLE
How can we hide the '0' value circle when lineCap = 'round'?

### ISSUE THREAD

**Issue by vc4u** [kottenator/jquery-circle-progress#108]
http://jsbin.com/nadozi/edit?html,js,output

Here is my JSBin.

I'm trying to initialize the circle with value = 0, but it shows a Dot as starting point. Only happens when lineCap is 'round'. How can I hide it and start as blank grayed circle when starting fresh circle?

![blank_circle](https://cloud.githubusercontent.com/assets/8048832/17461316/ec54d220-5ca5-11e6-98e3-dd27e6062af9.png)

**Comment by vc4u** [comment]
Just a quick update. I am now able to hide the initital round dot for  value=0, by modifying the drawArc() function like this:

```
drawArc: function(v) {
			if (this.getValue() > 0) { //introduced this value check so that arc is rendered only when value is > 0
				var ctx = this.ctx,
				  r = this.radius,
				  t = this.getThickness(),
				  a = this.startAngle;
				
				ctx.save();
				ctx.beginPath();
				
				if (!this.reverse) {
				ctx.arc(r, r, r - t / 2, a, a + Math.PI * 2 * v);
				} else {
				ctx.arc(r, r, r - t / 2, a - Math.PI * 2 * v, a);
				}
		
				ctx.lineWidth = t;
				ctx.lineCap = this.lineCap;
				ctx.strokeStyle = this.arcFill;
				ctx.stroke();
				ctx.restore();
			}
        }
```

Though a dirty hack, but seems like it is working for me. Not so sure if there is another approach to fix this.

**Comment by kottenator** [comment]
Firefox doesn't draw that "dot" but Chrome does. I consider this as a bug and I'll fix it in my library.

Meanwhile, you can use the following workaround:
```js
;(function() {
  // Override 'drawArc' - don't draw it when value is 0
  var _proto = $.circleProgress.defaults;
  var _drawArc = _proto.drawArc;
  _proto.drawArc = function(v) {
    if (v) {
      _drawArc.call(this, v);
    }
  };
})();

$('.circle').circleProgress({
    startAngle: -Math.PI / 2,
    value: 0,
    size: 200,
    thickness: 15,
    lineCap: 'round',
    fill: { color: '#2A94D6' },
    animation: false
});
```

**Comment by kottenator** [comment]
Fix committed to `master`.
