### ISSUE TITLE
Value not animating until at 1

### ISSUE THREAD

**Issue by IsaacAbrahamson** [kottenator/jquery-circle-progress#110]
I have a stopwatch I wanted to animate with a circular progress bar.

```js
$.circleProgress.defaults.size = 200;
$('.third.circle').circleProgress({
  value: 0,
  fill: {
    gradient: ["#581515", "#820a0a", "#9d3620"]
  }
});

function stopWatch() {
  var seconds = (timerFinish - (new Date().getTime())) / 1000;
  if (seconds <= 0) {
    clearInterval(timer);
    soundAlarm();
  } else {
    currentSeconds = Math.floor((timerFinish - new Date().getTime()) / 1000);
    $(this).find('strong').text(currentSeconds);
    var percent = Math.ceil(100 - ((seconds / (timerMinutes * 60)) * 100)) / 100;
    $('.third.circle').circleProgress('value', percent);
    var value = $('.third.circle').circleProgress('value');
    console.log(value);
  }
}
```

I know the stopwatch is running correctly, and in the console, it logs the correct percent for the time ex. 0.5 for 30 seconds left, but the circle is not animating until the value equals 1, and then it animates all the way around to 100%. The function does animate (somewhat weirdly) when stopWatch is run every second, but it does not work when the interval of stopWatch is a millisecond which I need for other parts.

**Comment by kottenator** [comment]
Your `stopWatch` function looks overcomplicated. [Here I've simplified it a bit](http://jsbin.com/puvoxi/4/edit?js,output) and it works.

**Comment by kottenator** [comment]
And I suggest to use `setTimeout(fn, customMilisecondsTillNextSecond)` instead of `setInterval(fn, 1000)` to have real seconds.

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.

**Comment by IsaacAbrahamson** [comment]
Sorry, Didn't see it till now, it works a lot better thanks a lot!
