### ISSUE TITLE
Layout tests with animation Test circle with value = 0.5, image background and reverse FAILED

### ISSUE THREAD

**Issue by dougt** [kottenator/jquery-circle-progress#112]
I am seeing the following error when running npm test.  Not sure if anyone else is seeing this or this is just my setup:

Firefox 48.0.0 (Ubuntu 0.0.0) Layout tests with animation Test circle with value = 0.5, image background and reverse FAILED
	Died on test #1 QUnit.asyncTest@/home/dougt/builds/jquery-circle-progress/node_modules/qunitjs/qunit/qunit.js:106:3
	@/home/dougt/builds/jquery-circle-progress/tests/tests.js:143:9
	@/home/dougt/builds/jquery-circle-progress/tests/tests.js:1:2
	: a.indexOf is not a function
	r.fn.load@/home/dougt/builds/jquery-circle-progress/bower_components/jquery/dist/jquery.min.js:4:18715
	@/home/dougt/builds/jquery-circle-progress/tests/tests.js:151:13
	Test.prototype.run@/home/dougt/builds/jquery-circle-progress/node_modules/qunitjs/qunit/qunit.js:790:4
	run/<@/home/dougt/builds/jquery-circle-progress/node_modules/qunitjs/qunit/qunit.js:877:5
	process@/home/dougt/builds/jquery-circle-progress/node_modules/qunitjs/qunit/qunit.js:593:4
	QUnit.start/<@/home/dougt/builds/jquery-circle-progress/node_modules/qunitjs/qunit/qunit.js:182:5
	
	
	Expected 9 assertions, but 1 were run
	QUnit.asyncTest@/home/dougt/builds/jquery-circle-progress/node_modules/qunitjs/qunit/qunit.js:106:3
	@/home/dougt/builds/jquery-circle-progress/tests/tests.js:143:9
	@/home/dougt/builds/jquery-circle-progress/tests/tests.js:1:2
	
	
Firefox 48.0.0 (Ubuntu 0.0.0): Executed 7 of 7 (1 FAILED) (4.023 secs / 4.004 secs)
npm ERR! Test failed.  See above for more details.

**Comment by andreiglingeanu** [comment]
#117 fixes it.

**Comment by kottenator** [comment]
@dougt: I've merged #118 to `master`. Could you try again now?

**Comment by dougt** [comment]
Didn't work for me:

https://gist.github.com/dougt/51cd638baa3e0fa733eb63220588f7bc

Maybe missing some step?

**Comment by andreiglingeanu** [comment]
@dougt [Run this](https://github.com/kottenator/jquery-circle-progress/blob/master/.travis.yml#L7-L9).

We probably should move this into an npm `post-install` script. I'm pretty sure we'll have to execute this commands even after switching to `npm` from `bower`, the [repo](https://github.com/Modernizr/Modernizr) will stay the same.

**Comment by dougt** [comment]
wfm!
