### ISSUE TITLE
Show one decimal place for the center percent

### ISSUE THREAD

**Issue by tamilust** [kottenator/jquery-circle-progress#122]
I tried updating the snippet to show one decimal point with ".toFixed(1)" but it just shows a 0 not the actual value after the decimal. Do you know how I would achieve this?

Snippet:
```js
append( '<span></span>' )
  .on('circle-animation-progress', function(event, progress, stepValue) {
    $(this).find('span').text(String(parseInt(100 * stepValue).toFixed(1) + '%'));
  });
```

**Comment by kottenator** [comment]
First of all, could you provide a working demo? Your snippet looks incomplete.
And as I can see, you use jQuery `append` a bit wrong: 

* you append `<span>` - jQuery switches its context to it
* then you're tring to find a `<span>` **inside** your appended `<span>`
* it doesn't exist, so nothing happens

You can do next (e.g.):

```js
circle.append( '<span></span>' ).end().on('circle-animation-progress', ...);
```

**Comment by kottenator** [comment]
I think I've got it. You do `parseInt(100 * stepValue)` - it always returns an integer _(obviously)_ so it will always show `.0` in a fractional part.

So just drop `parseInt` (and also `String`): 

```js
```

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
