### ISSUE TITLE
Progress Image

### ISSUE THREAD

**Issue by MohamedAmineOuali** [kottenator/jquery-circle-progress#123]
Hi,

Can I change the circle fill image dynamically when the animation is in progress?

Thanks in advance for any help you are able to provide.

**Comment by kottenator** [comment]
Yes, it's possible:

```js
el.circleProgress({...}).on('circle-animation-progress', function() {
  // in some condition
  var instance = el.data('circle-progress');
  instance.fill = {image: 'http://example.com/image.png'};
  instance.initFill();
});
```

However, image requires some time to load, so you may want to pre-load all the images first.

**Comment by kottenator** [comment]
@MohamedAmineOuali - I hope I've helped you. I'm closing this ticket, but feel free to reopen.
