### ISSUE TITLE
Reverse animation when going from 100 to 0

### ISSUE THREAD

**Issue by swillis93** [kottenator/jquery-circle-progress#124]
Hi,

I am using the progress for a minute countdown, and have got the animation working great up until the countdown reaches "full".  When the progress bar gets round to the full position, it then animates backwards to the beginning. What I would like is for when the progress bar is full, the start point will animate round to the end.

Here is a rough example of what I want to achieve: http://preloaders.net/preloaders/287/Filling%20broken%20ring.gif

Is this possible? If so then would you be able to help achieve this? 
Thanks

**Comment by kottenator** [comment]
[Here is an example](http://jsbin.com/vaduba/2/edit?js,output) for you.

**Comment by swillis93** [comment]
I've tried to add your code into my script but I am getting some real issues crashing the browser due to the countdown not letting animations finish.

[Here's a bin of roughly what I have](https://jsbin.com/dakebidife/edit?js,output)

Here you can see the seconds countdown goes backwards when reaching the full point. I would love if the reverse animation code you made could work with this.

Thanks for your help

**Comment by kottenator** [comment]
Try to change:
```js
$('.conference-countdown__circles-seconds').circleProgress('value', seconds);
```
to:
```js
$('.conference-countdown__circles-seconds').circleProgress('value', 1 - seconds);
```

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
