### ISSUE TITLE
Can i draw somehow 2 or more values in one circle

### ISSUE THREAD

**Issue by pwnz22** [kottenator/jquery-circle-progress#125]
Can i draw 2 or more  values in one circle with the different colors?  For example my first value is 20% of 100% circle and the second other 30%.

**Comment by kottenator** [comment]
Take a look at [#22](https://github.com/kottenator/jquery-circle-progress/issues/22#issuecomment-77723668), [#56](issuecomment-153184497) and [#106](https://github.com/kottenator/jquery-circle-progress/issues/106#issuecomment-238268455).

**Comment by pwnz22** [comment]
Thanks so much. The #56 what i needed.
