### ISSUE TITLE
Issue Creating Loop with On Click Listener

### ISSUE THREAD

**Issue by zman0404** [kottenator/jquery-circle-progress#127]
Thanks for the excellent work you have put in on this library! I'm running into an issue when I try and reset the circle on click.
```
$('#circle').circleProgress({
	    startAngle: 4.75,
	    value: 1.0,
	    size: 50,
	    reverse: false,
	    fill: {
	      gradient: ["#ffcc33"]
	    },
	    emptyFill: "rgba(0, 0, 0, 0)",
	    animation: { duration: 7000},

}).on('circle-animation-end', function(event) {
	  	       console.log('animation-end');
	  		$(this).circleProgress({ value: 1.0});
	  		
}).on('mouseup', function(event){

	$(this).trigger('circle-animation-end');
});
```

So the idea is to have the circle reset every time the animation ends (this case when it makes a full loop) OR reset when the circle is clicked. It seems as though this is resetting correctly when the animation ends but Animation is firing multiple times on mouseup (I've also tried a click listener with the same results).

Any suggestions or modifications I could try?

Thanks!

**Comment by kottenator** [comment]
I'd avoid re-using _inner_ `circle-animation-end` event. And I don't understand why do you need "... to have the circle reset every time the animation ends"? Here is [a snippet](http://jsbin.com/jivabi/3/edit?js,output) that may be what you need ;)

**Comment by zman0404** [comment]
Thanks for the reply! I'm using jquery-circle-animation as a slideshow progress wheel. The goal is to have a new slide appear each time the animation ends and then reset on the new slide.  Same action should take place on click.

**Comment by kottenator** [comment]
Ok, use custom event name then: [here is another snippet](http://jsbin.com/jivabi/2/edit?js,output).

**Comment by zman0404** [comment]
You rock! Thanks for you help and excellent library!

**Comment by kottenator** [comment]
You're welcome! ;)
