### ISSUE TITLE
custom layout demo - value not showing correctly

### ISSUE THREAD

**Issue by originmad** [kottenator/jquery-circle-progress#128]
Hi,

First of all thank you for such a great script. 

I want to implement one of your custom layout demo (http://output.jsbin.com/gabeli/8) to my project. 
But i realize that the value and animated number is not correct. value is 0.7 but animation always show "100". Is there any way to fix it. 

Best regards

**Comment by kottenator** [comment]
Try to change:

```js
.on('circle-animation-progress', function(e, v) {
```

to:

```js
.on('circle-animation-progress', function(e, p, v) {
```

... because the event listener takes 3 arguments:

1. jQuery event
2. Animation progress, which always starts at `0.0` and ends at `1.0`
3. Animation value - current animation frame value which starts at `0.0` and ends at `value`

**Comment by originmad** [comment]
Thank you. It's fixed now.

**Comment by kottenator** [comment]
You're welcome!
