### ISSUE TITLE
How to add text in the middle for the circle

### ISSUE THREAD

**Issue by shahidkarimi** [kottenator/jquery-circle-progress#129]
How to add text in the middle for the circle. This is none of use without the text functionality

**Comment by tidder99** [comment]
i'm far from good at this but this works for me
`$('#circle').circleProgress({
  value: 0.50,
  size: 300,
fill: { gradient: ['black', 'RED']}
}).on('circle-animation-progress', function(event, progress) {
  $(this).find('strong').html( '<i>Hi this is the text </i>');
});`

 the div where the  jquery-circle-progress put's the circle <strong> is where the text appears
`<div id="circle"> <strong></strong></div>`

CSS:
` #circle {
  position: absolute;
  top: 45%;
  left: 2px;
  width: 100%;


}  
`

strong {
  color:red;
position: absolute;
  top: 30%;
  left: 2px;
  width: 100%;
  text-align: center;
  line-height: 40px;
  font-size: 30px;

font-style: normal;
 
  font-weight: normal;
}  
`

**Comment by Christineyjones** [comment]
Thank you for this beautiful work. Is there any way to add labels at all? I have been searching for about an hour now and am kind of surprised that I cannot find any way to label the concentric circles version. I am thinking I will have to use tooltips but I am not sure that is going to be acceptable for the user...

**Comment by kottenator** [comment]
It's not a part of the library. But it's very easy to implement. For example, see #101.

**Comment by kottenator** [comment]
@shahidkarimi:

> This is none of use without the text functionality

Thanks for your warm words, cad.

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.

**Comment by regikono** [comment]
> i'm far from good at this but this works for me
> 
> ```js
> $('#circle').circleProgress({
>   value: 0.50,
>   size: 300,
> fill: { gradient: ['black', 'RED']}
> }).on('circle-animation-progress', function(event, progress) {
>   $(this).find('strong').html( '<i>Hi this is the text </i>');
> });
> ```
> 
> The `<div>` where the jquery-circle-progress put's the circle `<strong>` is where the text appears
> `<div id="circle"> <strong></strong></div>`.
> 
> CSS:
> 
> ```css
> #circle {
>  position: absolute;
>   top: 45%;
>   left: 2px;
>   width: 100%;
> }  
> 
> strong {
>   color: red;
>   position: absolute;
>   top: 30%;
>   left: 2px;
>   width: 100%;
>   text-align: center;
>   line-height: 40px;
>   font-size: 30px;
>   font-style: normal;
>   font-weight: normal;
> }  
> ```

Great! I didn't have paid attention on the strong tag. Working fine now, thank you a lot!
