### ISSUE TITLE
Value Format

### ISSUE THREAD

**Issue by MongoBongo** [kottenator/jquery-circle-progress#13]
Hi, 
I feel bad putting this as an issue seems as its more of a question. 
Is there anyway of changing the values required from 0.0 to just round numbers from 1 to 100?

Thanks for this library,

**Comment by kottenator** [comment]
You could set `{value: v / 100}`, where `v` is round integer from 1 to 100

**Comment by MongoBongo** [comment]
Thanks for the amazingly quick reply, 
Your suggestion works perfectly, and a whole lot more simple that I imagined. 
Thank you so much :)

**Comment by kottenator** [comment]
You're welcome ;)

**Comment by edho19** [comment]
is there possible to me to set the value max and min ?. My case is I want to set data-value in tag html w/ min value 0 and max value 100. Thanks :)

**Comment by kottenator** [comment]
@edho19 - you have value from `0.0` to `1.0`. Then you can transform it to whatever numeric range you want. Just do:

```js
// value is between 0.0 and 1.0
let min = 5, max = 125;
let convertedValue = min * (1 - value) + max * value; // 5 for 0.0, 125 for 1.0, 65 for 0.5
```
