### ISSUE TITLE
Integrating code into Wordpress

### ISSUE THREAD

**Issue by ozimm21** [kottenator/jquery-circle-progress#131]
Hi,

I'm very new to this- and am looking for a solution for a Wordpress site. 
This may be a dumb question but how do I integrate your script into a Wordpress site?
Also - is it possible to have a value with a separator inside the circle .e.g 30'412 ?

Thanks

**Comment by kottenator** [comment]
Sorry, I don't have any experience with Wordpress. But it should be easy, this is a simple JS that should work with any CMS or framework.

**Comment by ozimm21** [comment]
Thanks for responding- I'll see how I go- and let you know



________________________________

**Comment by kottenator** [comment]
How is it going? I don't see how I can help so I'm going to close this ticket soon.

**Comment by kottenator** [comment]
I hope you've solved this problem and successfully integrated `jquery-circle-progress` into Wordpress. I'm closing this ticket, but feel free to reopen.
