### ISSUE TITLE
Importing using ES6 but jQuery is loaded externally

### ISSUE THREAD

**Issue by dobromir-hristov** [kottenator/jquery-circle-progress#132]
Ok so my situation is a bit sticky. I am developing a WordPress theme for a client, but I am using ES6 with Babel and Browserify for my custom code. Problem is I cant just deregister jQuery because the majority of WP plugins require it.
So in every ES6 module I just `const $ = window.jQuery` (because I just couldn't make browserify shim to work properly). 
But now when I `import 'jquery-circle-progress'` I jsut get that circleProgress is not a function of jQuery. Any suggestions how I should proceed ? 
At this point I just added the whole plugin into my Libraries JS stack, and its available everywhere, but that's not cool.

**Comment by kottenator** [comment]
Seems like a bug. I'll take a closer look.

**Comment by andreiglingeanu** [comment]
@dobromir-hristov I fixed that problem by marking `jquery` module as a global variable that comes from `window.jQuery`, [like that](https://github.com/Creative-Themes/build-process/blob/02cba1d695c872ae33c7ba72c4e37d1bb2b731c0/webpack.config.js#L181). I am using _webpack_, though. I bet browserify have such an option too.

**Comment by andreiglingeanu** [comment]
@kottenator And I'm having no problem with `jquery-circle-progress` picking up `window.jQuery`, as long as you indicate webpack that `jquery` module refers to `window.jQuery` variable. No one even cares about the source of `jquery` module.

**Comment by andreiglingeanu** [comment]
> I bet browserify have such an option too.

[Confirmed.](http://stackoverflow.com/a/23129051/3220977)

**Comment by kottenator** [comment]
@andreiglingeanu - I think I've found a bug in the UMD template I'm using ([this line](https://github.com/kottenator/jquery-circle-progress/blob/1.2.0/dist/circle-progress.js#L18) should return a value, not a function). I'll take care.

**Comment by kottenator** [comment]
So, after investigation, it's not a UMD bug but rather [UMD specific decision](https://github.com/umdjs/umd/issues/87#issuecomment-271195414).

They decided to export a factory function, not `jQuery`. The function needs to be _called_ to initialiaze the plugin:

```js
import jcp from 'jquery-circle-progress';
jcp();
```

I find this decision too complicated, so I've updated the UMD code. Now this will work (as expected):

```js
import 'jquery-circle-progress'; // that's it, plugin is initiated using `$ = require('jquery')`
```

I'm releasing version `1.2.1` now.

**Comment by kottenator** [comment]
`jquery-circle-progress@1.2.1` released. Now few words about `browserify-shim` configuration: see [my gist](https://gist.github.com/kottenator/0623cf601ea167f31cfb3150d8b25b10).

I believe the bug is fixed. I'm closing this ticket. @dobromir-hristov - please, check if everything works now. Feel free to reopen this ticket.
