### ISSUE TITLE
"crazy demo" not working, js fails to load

### ISSUE THREAD

**Issue by cybersholt** [kottenator/jquery-circle-progress#133]
The demo listed in the readme fails to load script @ http://kottenator.github.io/jquery-circle-progress/dist/circle-progress.js

replaced with https://cdnjs.cloudflare.com/ajax/libs/jquery-circle-progress/1.2.0/circle-progress.js 

and it's now working @ http://output.jsbin.com/moqocunupi/1

**Comment by kottenator** [comment]
Thanks for reporting. It's fixed now in `master`.

**Comment by cybersholt** [comment]
thanks @kottenator
