### ISSUE TITLE
jquery-migrate: easing function "jQuery.easing.circleProgressEasing" should use only first argument

### ISSUE THREAD

**Issue by mstojanovv** [kottenator/jquery-circle-progress#137]
I have problem when I include the `jquery-migrate` plugin. The progress percent is shown as `0`. When I remove the `jquery-migrate`, plugin works good.

Any ideas? Thanks in advance.

**Comment by kottenator** [comment]
Could you, please, create a demo? (JSBin, etc)

**Comment by mstojanovv** [comment]
Yes sure.
Take a look at this [JSBin](https://jsbin.com/vivimeceru/1/edit?html,css,output)

Thanks.

**Comment by kottenator** [comment]
Sorry for such a delay. Finally I have time to fix this.

**Comment by kottenator** [comment]
Bug fixed. `jquery-circle-progress@1.2.2` released.

**Comment by mstojanovv** [comment]
Thanks, working good now.
