### ISSUE TITLE
Draw line for setpoint/target value

### ISSUE THREAD

**Issue by snazzypants** [kottenator/jquery-circle-progress#138]
Hi!  I was wondering if it was possible to draw a line that intersects the arc at a given setpoint or target value.  I was looking at possibly using #84 as a baseline. That solution works very nicely for values that are over the target, but it does not visualize well for values that are below the target.

Thanks!

**Comment by kottenator** [comment]
Hi, @snazzypants! 

Could you, please, specify - how should this line look like? A screenshot / hand drawing will do ;)

**Comment by kottenator** [comment]
@snazzypants, I hope you've solved this problem. I'm closing the ticket due to a month of waiting for your answer. Feel free to reopen it if you still need help.
