### ISSUE TITLE
duration does not work 

### ISSUE THREAD

**Issue by rahulgautam** [kottenator/jquery-circle-progress#139]
```js
$('#circle').circleProgress({
  value: 0.75,
  size: 150,
  duration: 4000,
  lineCap: 'round',
  fill: {color: '#FF4107'}
}).on('circle-animation-progress', function(event, progress, value) {
  console.log(value);				
});
```

It always complete progress on the same time, Seems like duration does not affect it.
Please let me know if I am doing anything wrong.

**Comment by kottenator** [comment]
Hi, @rahulgautam!

You're right, `durartion` doesn't work in your case because you're setting it incorrectly.

According to [docs](https://github.com/kottenator/jquery-circle-progress), `duration` is a part of `animation` config:

```js
$('#circle').circleProgress({
  animation: {
    duration: 4000,
    easing: "circleProgressEase"
  },
  // ...
});
```
