### ISSUE TITLE
Progress circle with color based on progress

### ISSUE THREAD

**Issue by Eyedicious** [kottenator/jquery-circle-progress#140]
Hello,

First of all, I love your plugin, I'm currently using it in a project of mine, but I've hit a snag.

I'm trying to create a circle, where the first 33% is red, the next 33% is yellow and the final 33% is green. Not necessarily with those divisions, but the idea is, the "better" the progress, the more "positive" the feedback.

I've been playing around with the color fill, but havn't been able to find the precise way of achieving this.
Currently I got this 
![progress_bar](https://cloud.githubusercontent.com/assets/3646993/24554021/75f372d0-162c-11e7-98d7-11ca7756818a.png) and I'm trying to get something like this: ![progress_bar_indicator](https://cloud.githubusercontent.com/assets/3646993/24554052/8817a6b6-162c-11e7-9c35-9c53405b3d40.png)

The idea is btw, if the circle is 75% filled, it's 33% red, 33% yellow and 9% green. The code to initialize my circle is:

```js
$('.third.circle').circleProgress({
  value: +$('.third.circle').data("value").replace(",","."),
  size: 60,
  thickness: 10,
  lineCap: "round",
  fill: {
    gradient: ['red', 'yellow', 'green'],
    gradientAngle: 5 / (Math.PI * 3)
  }
}).on('circle-animation-progress', function (event, progress, stepValue) {
  //drawconfidence();
  var canvas = $(this).circleProgress('widget');
  $(this).find('strong').text((stepValue * 100).toFixed(2));
  $(this).find('strong').css("color", GreenYellowRed(stepValue * 100));
});
```

Any help would very much be appreciated!

**Comment by kottenator** [comment]
Hi, @Eyedicious! 

I believe [this comment](https://github.com/kottenator/jquery-circle-progress/issues/58#issuecomment-148087170) should help you ;)

**Comment by Eyedicious** [comment]
Ah yes, cheers, ,thank you!

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
