### ISSUE TITLE
Bug for html config option data-emptyFill

### ISSUE THREAD

**Issue by ignoreswing** [kottenator/jquery-circle-progress#142]
Dear author,
Thank you for providing this great plugin. 

I found a bug for html initial config. When I try to initialize circle-progress using html config, most of them (e.g. data-fill, data-thickness, data-size, etc) work fine as expected.
However, **data-emptyFill** would fail (remain using default setting). 

>Here is a simple and clean repo: 
https://jsfiddle.net/ignoreswing/fvfnuqdu/

In the above repo, _circle1_ use JS config and _circle2_ use html config.

**What is Expected?** 
Both of them has emptyFill color, yellow.
**What is actually happening?** 
_circle2's_ emptyFill has not taken effect.
**Bug version**
1.1.4 & 1.2.1 (I don't known why 1.2.1 can't work at jsFiddle)

I traced the source code.
I guess this might be a case-sensitive problem.
In JS code, you wrote `this.emptyFill;`, while the attribute `data-emptyFill` from html would cause an all lowercase string, i.e., emptyfill.

I would appreciate it If this issue can be fixed.
Thank you.

**Comment by kottenator** [comment]
Hi, @ignoreswing! Have you tried `data-empty-fill`?

**Comment by ignoreswing** [comment]
It's work!!
Thank you for your kindness reply and sorry for this stupid question..  ^^b
