### ISSUE TITLE
1.2.1 issue 

### ISSUE THREAD

**Issue by robbisy** [kottenator/jquery-circle-progress#144]
Hi Rostyslav 
With 1.2.1 it gets me Uncaught TypeError: Cannot set property 'circleProgress' of undefined
I've made you two demo with the same code but only change jquery-circle-progress
 version from 1.2.0  to 1.2.1. The first one work but not the second
[ version 1.2.0](https://jsfiddle.net/fvfnuqdu/4/)
[version 1.2.1](https://jsfiddle.net/fvfnuqdu/5/)

**Comment by kottenator** [comment]
Hi, @robbisy!

It's [a bug](https://github.com/cdnjs/cdnjs/issues/11120) of CDNJS-hosted version of my library. I've created a ticket for them to fix it.

Meanwhile:

* you can use my original JS code (e.g. install it / add as a dependency with NPM / Bower)
* or you can try a different CDN (e.g. [this one](https://cdn.rawgit.com/kottenator/jquery-circle-progress/1.2.1/dist/circle-progress.min.js)).

*UPD*: when I'll release new `jquery-circle-progress@1.2.2` and it'll appear on CDNJS - the problem should be gone.

**Comment by kottenator** [comment]
After discussion in [the CDNJS ticket](https://github.com/cdnjs/cdnjs/issues/11120), thanks to @PeterDaveHello, the _fixed_ `jquery-circle-progress@1.2.1` version will appear on CDNJS soon.

**Comment by kottenator** [comment]
New `jquery-circle-progress@1.2.2` version released. As soon as it's fetched by CDNJS - this bug should be fixed.

I've also described workarounds for version 1.2.1 (see above) so I'm closing this ticket.

**Comment by kottenator** [comment]
FYI - CDNJS has fetched the 1.2.2 version and [it works now](https://jsfiddle.net/4n597qr3/).

**Comment by robbisy** [comment]
@kottenator Thanks a lot
