### ISSUE TITLE
circleProgress is not a fuction

### ISSUE THREAD

**Issue by devope** [kottenator/jquery-circle-progress#147]
Hi!

I get this error using WebPack: "circleProgress is not a fuction".

My `script.js`:

```js
require('jquery-circle-progress/dist/circle-progress');

$("#dial-1").circleProgress({
    value: 23,
    size: 60,
    lineCap: 'round',
    fill: {
      gradient: ["#005bff", "#005bff"]
    },
    thickness: 33
})
```

jquery loads by `webpack.ProvidePlugin`:

```js
new webpack.ProvidePlugin({
    $: 'jquery',
    jquery: 'jquery',
    jQuery: 'jquery',
    Mustache: 'mustache',
})
```

**Comment by andreiglingeanu** [comment]
@devope If you can come up with a minimal repo on GitHub which reproduces that error I might be able to help you.

**Comment by kottenator** [comment]
@devope - I'll try to help you.

First of all - use `require('jquery-circle-progress')` instead of `require('jquery-circle-progress/dist/circle-progress')`. It's the same right now, but shorter. And someday I may rename `dist` to `lib` (e.g.) but `require('jquery-circle-progress')` will still work correctly.

**Comment by kottenator** [comment]
Another question - could you try to use it without `webpack.ProvidePlugin`, just with the regular WebPack module loader?

**Comment by jondkinney** [comment]
This took me a bit... here's what I had to do to get `circleProgress` to be recognized in the context of webpacker in a new rails app where I already had jquery loaded via the asset pipeline.

From: `app/javascript/packs/application.js`

```javascript
/* eslint no-console:0 */
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.
//
// To reference this file, add <%= javascript_pack_tag 'application' %> to the appropriate
// layout file, like app/views/layouts/application.html.erb

console.log('Hello World from Webpacker');

import $ from 'jquery';
import 'jquery-circle-progress';

$(document).on('turbolinks:load', function() {
  $('#circle').circleProgress({
    value: 0.75,
    size: 80,
    fill: {
      gradient: ["red", "orange"]
    }
  });
});
```

You can move this out to a different folder structure as it suits you, but they key is allowing `circleProgress` to find and have jQuery loaded for it in the right order.

**Comment by kottenator** [comment]
Yes, in my library, there's UMD which does (for NPM environment):

```js
var jQuery = require('jquery');
```

Probably `webpack.ProvidePlugin` was conflicting with this mechanism in some way.

@jondkinney - thanks for the investigation. Are you OK now? May I close this ticket? Or is there something that I should do?

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
