### ISSUE TITLE
Ionic compatibility

### ISSUE THREAD

**Issue by johannbou** [kottenator/jquery-circle-progress#148]
Hello and thanks for your work,

Is this library available with Ionic Framework and the Cordova environment? I tried to insert it in a project but unfortunately the gauges do not display ... There is only the texts (I recovered one of your derived gauges) (full and custom).
The console does not indicate an error, and I can easily operate the gauges on a simple HTML project.
Do you have any information about Ionic?

Thanks in advance.

**Comment by kottenator** [comment]
Hi, @johannbou!

No, I have no information about Ionic. Does it work fine with jQuery? If it does - then my plugin should work fine too, I guess.

**Comment by kottenator** [comment]
@johannbou - I've found [this comment](https://forum.ionicframework.com/t/use-ionic-with-jquery/1120/6):

> You just place the jQuery file before AngularJs and you will have full access to jQuery as `jQuery()` or as using selectors `angular.element()`

Have you done that? Does `jQuery()` work in your code?

**Comment by johannbou** [comment]
Thanks to your instructions, all works ! Thanks man, it helps me for my school project ! And I hope it will helps people :)

**Comment by kottenator** [comment]
You're welcome! Thanks for the good words! ;)

**Comment by johannbou** [comment]
![screenshot_20170530-234718 1](https://cloud.githubusercontent.com/assets/29005225/26652294/b8bfe82a-464f-11e7-91e2-c031405127be.png)

**Comment by kottenator** [comment]
Looks pretty! Good luck with your app ;)

Or did you want to show that something's wrong?

**Comment by johannbou** [comment]
Thank you !
No, all work well ! :)
