### ISSUE TITLE
CircleProgress won't update via redraw or update

### ISSUE THREAD

**Issue by ChrisRab** [kottenator/jquery-circle-progress#150]
Hi,

I'm having a strange issue, when I try to update my CircleProgress with a settimeout function, it won't update. It moves like 1% and get right back where it was.

When I copy and paste the same code in the console, it works.
Same behavior in Chrome and in Firefox.

I don't get what is wrong, here are attached my sources.

**Comment by kottenator** [comment]
Hi, @ChrisRab!

Could you, please, create a working demo on JSBin or JSFiddle?

**Comment by ChrisRab** [comment]
Thanks for reactive answer.
I tried to reproduce the issue withotu success.

I replaced square brackets by dot in my code when possible ,like
`aCharts['gpu'+i]['fanspeed']['chart']`
into:
`aCharts['gpu'+i].fanspeed.chart`

Now the timeout function is still bugy the when I call my update function in console it works (it didn't before).

I'll keep trying to find the source of the issue and I'll keep you informed.

**Comment by ChrisRab** [comment]
Found my issue.

100% my bad, I was calling a method that was redrawing once more the circle progress.
So stupid, the simpliest answer is always the last place one looks.

You're plugin is 100% working, thanks for your time dude.

Wish you the best.

**Comment by kottenator** [comment]
Sorry that I didn't have a chance to help you. 
But I'm glad that you've managed to help yourself ;)
Good luck with your project!
