### ISSUE TITLE
Problems with gradient Color

### ISSUE THREAD

**Issue by steve231293** [kottenator/jquery-circle-progress#152]
Hello, Can you help me how to make gradient color like this [http://prntscr.com/fsme7y](http://prntscr.com/fsme7y)
Start with first color then end with second color

**Comment by kottenator** [comment]
What you need is a _conical gradient_ fill - see #73.

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
