### ISSUE TITLE
Progress event

### ISSUE THREAD

**Issue by lossius30** [kottenator/jquery-circle-progress#153]
Hi,
I'm trying to add simple text over the circle by listening to the `circle-animation-progress` event and that work but the event is triggered even if I set start value to `0`. While this animation, nothing change on my screen.

```js
var elem = $('#test');

elem.append('<span class="percent">-</span>');

elem.circleProgress({
  value: 0
}).on('circle-animation-progress', function(event, animationProgress) {
  $('.percent', this).html(Math.round(animationProgress * 100)+'%');
});

```
Thanks

**Comment by kottenator** [comment]
I'm not sure if it's a bug or a feature 😄 

You animate the circle. The animation runs in a predefined time frame, despite the fact if the value is `0` or something else.

In fact, you may not need `animationProgress`:

```js
var elem = $('#test');

elem.append('<span class="percent">-</span>');

elem.circleProgress({
  value: 0
}).on('circle-animation-progress', function(event, animationProgress, stepValue) {
  $('.percent', this).html(Math.round(stepValue * 100)+'%');
});
```
So nothing will happen visually...

Okay, okay, it looks like a bug 😈 . But now you understand how it works. I can prevent `circle-animation-progress` event from triggering (when start/stop will still trigger). Do this sound correct?

**Comment by lossius30** [comment]
That works ! Why animationProgress is the second argument if it's for internal purposes ? Because what we wanna know first is the value of what we see, not what the engine do :)

**Comment by kottenator** [comment]
@lossius30 - I agree with you now, but back then it was perfectly logical to me :)

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
