### ISSUE TITLE
Countdown 60 seconds

### ISSUE THREAD

**Issue by jensej** [kottenator/jquery-circle-progress#154]
Hello.
Is any possible to countdown 60 seconds, and on each second progres circle per 1/60, and when is 60 then stop animation?
Thanks

**Comment by kottenator** [comment]
The answer is "yes" but you need to figure out how to code a countdown timer in JS ;)

And then:

```js
countdownTimer.on('each-second', secondsLeft => {
});
```

**Comment by kottenator** [comment]
@jensej - here is a [simple JS countdown](http://jsbin.com/matopug/2/edit?js,console) example that I've made for you.

**Comment by kottenator** [comment]
I had an inspiration - here's [the full working demo](http://jsbin.com/nibujuj/2) for you.
