### ISSUE TITLE
How to destroy?

### ISSUE THREAD

**Issue by Ontokrat** [kottenator/jquery-circle-progress#156]
I can't see in the API a method to destroy the plugin.
Is it possible & if yes, how?
Thanks

**Comment by kottenator** [comment]
First of all, thank you for finding this missing feature ;) I think I'll add it in the next version.

And for now, the only way to destroy it is something like this:

```js
var el = $(...);
el.circleProgress(...);
var circleProgress = el.data('circle-progress');
$(circleProgress.canvas).remove();
el.removeData('circle-progress');

```

**Comment by Ontokrat** [comment]
Thanks @kottenator - looking for this update.
