### ISSUE TITLE
How should we add fillText properly?

### ISSUE THREAD

**Issue by mweiss27** [kottenator/jquery-circle-progress#157]
I'm trying to configure some `fillText` on the canvas, but I'm getting some undesired behavior.

Things I've tried thus far:

**Initializing my progress ring, and directly after setting the fillText.**

```js
$('#ring').circleProgress({ ..... });
$("canvas")[0].getContext("2d").fillText("Test", 50, 50);
```

This approach results in no text being displayed.

**Attaching a listener to circle-inited, and setting the text there.**

```js
$("#ring").on("circle-inited", function() {
   $("canvas")[0].getContext("2d").fillText("Test", 50, 50);
});
$('#ring').circleProgress({ ..... });
```

**I also tried attaching to circle-animation-end just to see if that would make a difference, but no dice.**

The only thing that seems to work is attaching to `circle-animation-progress`, but that obviously isn't the approach I want to take.

I have console outputs to verify that my event listeners are getting called. Is there something else I should be doing to get this working properly?

Thanks

**Comment by kottenator** [comment]
Please, take a look at #39.

**Comment by mweisspt** [comment]
Perfect, thank you!

**Comment by kottenator** [comment]
> The only thing that seems to work is attaching to `circle-animation-progress`, but that obviously isn't the approach I want to take.

Well, that's what I've done in that ticket :) If you don't want to do this, you can patch the `.drawFrame(v)` internal method:

```js
var _originalDrawFrame = $.circleProgress.defaults.drawFrame;
$.circleProgress.defaults.drawFrame = function(v) {
  _originalDrawFrame.call(this, v);
  var ctx = this.ctx,
      s = this.size,
      sv = (100 * v).toFixed(),
      fill = this.arcFill;
  
  ctx.save();
  ctx.font = "bold " + s / 2.5 + "px sans-serif";
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillStyle = fill;
  ctx.fillText(sv, s / 2, s / 2);
  ctx.restore();
};  
```

**Comment by mweisspt** [comment]
Well I said that because it was working, but drawing multiple strings. Your way provides the proper way to use that route, so it's certainly viable.

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
