### ISSUE TITLE
Inconsistence between docs and code for circleProgressEase

### ISSUE THREAD

**Issue by Chosko** [kottenator/jquery-circle-progress#158]
Hi,
docs say to use "circleProgressEase" while in code the function is named "circleProgressEasing".

For this reason when I tried to use this html

```html
    <div
      class="circle-progress"
      data-animation="{
        &quot;duration&quot;: 2000,
        &quot;easing&quot;: &quot;circleProgressEase&quot;
      }"
    >
    </div>
```

I got this error: `r.easing[this.easing] is not a function`.

I already worked around that, but it might be better to update the documentation

**Comment by kottenator** [comment]
Could you, please, make a pull-request to `README.md`?

**Comment by kottenator** [comment]
Ok, I see you don't have time for this. I've updated the `README.md`.
