### ISSUE TITLE
How to show the decimal value inside the circle

### ISSUE THREAD

**Issue by mavinothkumar** [kottenator/jquery-circle-progress#159]
Hi,
I would like to show the decimal value inside the circle with progress like 10.3, 30.22 , please let me know how to achieve this

**Comment by kottenator** [comment]
See #157 - in the code snippet given there, change `sv = (100 * v).toFixed()` to `sv = (100 * v).toFixed(1)` to get the decimal digit(s).

If you don't need _fancy text render inside the canvas_, just do:

```js
el.circleProgress(...).on('circle-animation-progress', function(e, p, v) {
  textPlaceholder.text((v * 100).toFixed(1));
});
```

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.

**Comment by mavinothkumar** [comment]
Am sorry for the delay response and thanks for your solution, Actually I sort out the issue by adding 
`textPlaceholder.html(((value.toFixed(1))* progress).toFixed(1));`
