### ISSUE TITLE
How to actually set a new value without resetting the circle?

### ISSUE THREAD

**Issue by emzero** [kottenator/jquery-circle-progress#16]
So I've been looking through several circle progress plugins and I find yours is nice, elegant and animated.

Problem is I don't know how to update the value without resetting the circle.

Let me explain:
I have a 5 step client side process, at first the progress is at 0%... when the first step is finished, the circle should animate to 20% (0.2), when the second step is finished, it should animate to 40% (0.4) WITHOUT going back to 0 and then to 40, and so on.

Without this functionality your progress plugin is kind of useless =(

Hope I'm missing something. 
Thank you!

**Comment by kottenator** [comment]
You have two ways to do this:

1. Without animation
--------------------------
```js
var circle = $('#circle').circleProgress({ animation: false });

function step(v) {
    circle.circleProgress({ value: 0.2 });
}

setTimeout(function() { step(0.2); }, 1000);
setTimeout(function() { step(0.4); }, 2000);
setTimeout(function() { step(0.6); }, 3000);
setTimeout(function() { step(0.8); }, 4000);
setTimeout(function() { step(1.0); }, 5000);
```

2. With animation
----------------------
```js
var circle = $('#circle').circleProgress();

function step(v) {
    circle.circleProgress({
        animationStartValue: circle.data('circle-progress').value,
        value: v
    });
}

setTimeout(function() { step(0.2); }, 1000);
setTimeout(function() { step(0.4); }, 2000);
setTimeout(function() { step(0.6); }, 3000);
setTimeout(function() { step(0.8); }, 4000);
setTimeout(function() { step(1.0); }, 5000);
```

But I will think about how to simplify this in the next version.

**Comment by rahulsukla** [comment]
Its working fine for circles, but values inside updating from zero
$(this).find('strong').html((progress * value).toFixed(0) + '%');

**Comment by kottenator** [comment]
First of all, in version `1.1.3` I've implemented a convenient method for this: `circle.circleProgress('value', newValue)`.

As for your question - as I understand your example, `progress` is a `progressValue`. In this case the behavior is corect: `progressValue` changes from `0.0` to `1.0` and indicates current progress of the animation. What you probably want to display is `stepValue`:

```js
// example for v1.1.3
var circle = $('#circle').circleProgress({
  value: 0.2
}).on('circle-animation-progress', function(event, progressValue, stepValue) {
  $(this).find('.value').text(stepValue.toFixed(2));
});

setTimeout(function() { circle.circleProgress('value', 0.5); }, 1000);
setTimeout(function() { circle.circleProgress('value', 0.7); }, 2000);
setTimeout(function() { circle.circleProgress('value', 0.99); }, 3000);
```

And here is [my demo](http://jsbin.com/sucabu/2/edit?html,js,output)
