### ISSUE TITLE
Timer inside the circle

### ISSUE THREAD

**Issue by Yeeroz** [kottenator/jquery-circle-progress#160]
Hello,

First of all **thank you for your job**.

I try to put a timer inside the circle.

For example for 12 seconds, I do this:

```js
$('.circle').circleProgress({
  value: 1,
  animation: { duration: 12000, easing: "linear" } 
}).on('circle-animation-progress', function(event, progress) {
  $(this).find('strong').html(Math.round(12 * progress) + '<i>Sec</i>');
});
```

It works very well, but now if I try to do the same thing for 2 minutes it does not work anymore, example:

```js
 $('.circle').circleProgress({
  value: 1,
  animation: { duration: 120000, easing: "linear" } 
}).on('circle-animation-progress', function(event, progress) {
  $(this).find('strong').html(Math.round(2 * progress) + '<i>Min</i>');
});
```

Do you have a solution?
Thank you

**Comment by kottenator** [comment]
@cheick92i - I don't think you should rely on `duration` when you need a timer.

Just a week ago I've helped with a similar problem - 60 seconds countdown. See #154.

**Comment by kottenator** [comment]
@cheick92i - did my comment solve your problem? I'm going to close this ticket (later today) unless you still have the problem.

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.

**Comment by kottenator** [comment]
@cheick92i - [exclusively for you](http://jsbin.com/muzaqah/2/edit?html,js,output) ;)
