### ISSUE TITLE
'circle-inited' event not working

### ISSUE THREAD

**Issue by donomron** [kottenator/jquery-circle-progress#162]
I'm trying to do some calculation for circle fill color when progress starts. This event is the right place for it but it seems that it is not fired at all.

```js
$('#circle').circleProgress({
   value: 0.4
}).on('circle-inited',function(){
  console.log('inited');
})
```

**Comment by kottenator** [comment]
Hi, @donomron!

Yes, that's a known ~issue~ design problem. The `init` event is triggered _synchronously_ with the circle creation (which is also synchronous). If you really want to listen to it - you need to subscribe to it _before_ the circle creation:

```js
$('#circle').on('circle-inited', function() {
  console.log('inited');
}).circleProgress({
  value: 0.4
});
```

**Comment by kottenator** [comment]
... but since the circle creation is synchronous, this event is not very helpful - you can just do something _right after_ you've created the circle. Though, there might be useful cases, I believe...

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
