### ISSUE TITLE
How to use jquery.appear plugin with circular progress bar plugin

### ISSUE THREAD

**Issue by krishnapreejith** [kottenator/jquery-circle-progress#168]
When I use jquery.appear plugin with my circular progress bar, to load when it is visible on the screen, it does not working

**Comment by kottenator** [comment]
Try to read #8 carefully.

**Comment by krishnapreejith** [comment]
But it's not working for me...Could you please explain the code

**Comment by kottenator** [comment]
That's too abstract. Please, create a live demo somewhere (better on JSBin / JSFiddle / CodePen, so I can fork & edit it).

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
