### ISSUE TITLE
emptyFill not working

### ISSUE THREAD

**Issue by danimanca** [kottenator/jquery-circle-progress#169]
Hi there,

I am using the emptyFill parameter to color the empty fill part of the circle, however it will not change the color to what I want:

I am using it like so:

`
emptyFill: {
 color: '#CCCCCC'
}
`

the color changes but to black, not grey...

**Comment by kottenator** [comment]
@danimanca - according to [documentation](https://github.com/kottenator/jquery-circle-progress), you should specify the color as follows:

```js
el.circleProgress({
  emptyFill: '#CCCCCC'
  // ...
})
```

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
