### ISSUE TITLE
Circle disappears

### ISSUE THREAD

**Issue by tomm-m** [kottenator/jquery-circle-progress#170]
Hey there,
despite the title, I'm not really sure about what's happening here.
I'm building an audio player for a website (the site is not live yet but I've attached an image of the player) and the progress circle works just fine with the first track I select but then disappears when I switch to another track.

The player is an instance of an Album object and the circle is initialized when the album code is created. When a track needs to be played, this function is fired:
```javascript
playSound: function() {
    [...things]
    var audio = new Audio(this.currentPath);
    this.cachedTracks[this.currentTrack] = audio; // Caching the playing audio object
    audio.ontimeupdate = function() { events.emit('progress'); };
    audio.play();
    [other things...]
},
```
it essentially binds the _ontimeupdate_ event to another function, that looks like this:
```javascript
updateProgressBar: function() {
    if( !this.undefined() ) {
        var curr = this.cachedTracks[this.currentTrack];
        var prog = curr.currentTime / curr.duration;
        this.items.progressBar.circleProgress('value', prog);
    }
}
```
I determine the current track's progress value and update the progress circle accordingly.

As I've already written, this works just fine for the first track I select but selecting another track will make the circle disappear (the canvas is still there tho).
I've looked at jquery-circle-progress' code but couldn't figure out why, any ideas?
Thanks a lot 

![audio-player](https://user-images.githubusercontent.com/9594553/32406020-ae988662-c170-11e7-9087-2ad37271b2dc.png)

**Comment by tomm-m** [comment]
Alright, I have solved it and it was actually much simpler than I thought :/ I'm slapping my own face right now. The problem was **for just one damn frame the value set was Not a Number**. I have solved it with a simple `isNaN()` check.

Two lessons here:
1. Always check your damn variables.
2. If your circle disappears you have probably passed an incorrect value to the function.

**Comment by kottenator** [comment]
I'm glad that you've figured out everything by yourself ;) Is there anything left in this ticket? I want to close it.

**Comment by tomm-m** [comment]
Nope, nothing else :) You could make it throw an error when a NaN value is passed, tho. So people like myself would quickly find out the reason why it isn't working

**Comment by kottenator** [comment]
That's a good idea, I'll think about it ;)
