### ISSUE TITLE
Empty fill color only supports default color

### ISSUE THREAD

**Issue by danimanca** [kottenator/jquery-circle-progress#171]
Am I right in the way I understand the docs, the emptyFill property only supports the default color currently, correct?
If that's so, when we will have support for any colors?

**Comment by kottenator** [comment]
No, that's not correct, currently `emptyFill` supports any colors, but no gradients and no images: 

```js
emptyFill: '#fc0'
```

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
