### ISSUE TITLE
Making into a semi circle

### ISSUE THREAD

**Issue by MarvellousUbani** [kottenator/jquery-circle-progress#173]
Hello,
Nice plugin here.

Wondering how I can make this into a semi circle instead of a circle and set the values so it doesn't go past the semi circle.

I understand how semi circles are created using just canvas. I tried tweaking and it doesn't really work here. 

Will really appreciate the help.

**Comment by kottenator** [comment]
Hi!

Is [this](https://github.com/kottenator/jquery-circle-progress/wiki/Custom-layouts#arc-layout) what you need?

**Comment by MarvellousUbani** [comment]
Hello,

Yes exactly. Your awesome man!!. .. Thanks

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
