### ISSUE TITLE
Is it possible to fill the bar with one color at each fill percentage?

### ISSUE THREAD

**Issue by AugustoMarcelo** [kottenator/jquery-circle-progress#174]
I have a bar with 180 in size and would like to fill it with 4 colors, one being every 25% fill. I tried to do it this way, but some colors take up more space than others and in addition they repeat themselves.
```js
$('.progress-bar').circleProgress({
  value: .60,
  size: 180.0,
  startAngle: Math.PI*1.5,
  fill: {
    //color: 'rgb(250,250,250)'
    gradient: ['#e74c3c', '#e67e22', '#f1c40f', '#27ae60'],
    gradientAngle: Math.PI*1.5
  },
  emptyFill: 'rgba(200,200,200, 0.2)',
  animation: {
    duration: 3000
  },
  lineCap: 'round'
}).on('circle-animation-progress', function(event, progress) {
  $(this).find('strong').html(
    Math.round((100 * progress)*$(this).circleProgress('value')) + '<span>%</span>'
  );
});
```

**Comment by kottenator** [comment]
Is #56 what you're looking for?:

<img width="154" alt="image" src="https://user-images.githubusercontent.com/371674/33397242-17ac1d92-d519-11e7-9572-5924cee4e406.png">

**Comment by AugustoMarcelo** [comment]
Almost this, but with a gradient color change. See, in the figure below, that the desired effect is produced up to 50%. But after that, the colors repeat themselves.

![capturar](https://user-images.githubusercontent.com/11545976/33402706-91433b92-d544-11e7-91e4-f175c8197ce0.PNG)

**Comment by kottenator** [comment]
The only way to do this is via `image` fill, because currently `<canvas>` doesn't support _conical gradient fill_.

See #73, especially [this comment](https://github.com/kottenator/jquery-circle-progress/issues/73#issuecomment-165865792) with an example.

**Comment by AugustoMarcelo** [comment]
I got an effect similar to what I wanted using image. I had to use lineCap: 'butt', because 'round' did not work as I would have liked. Thanks!
