### ISSUE TITLE
maxTimeOut

### ISSUE THREAD

**Issue by tekbahadur1996** [kottenator/jquery-circle-progress#178]
There is a default **maxTimeOut** set already in `jquery-circle-progress`. How can I remove that? 

I am using `jquery-circle-progress` in file uploading but when I upload a big sized file (size > 200 MB) then the circle completes before the file upload. And if the data-transmission is slow then also I will get the same problem. It is actually not a issue but a problem that I am facing.

**Comment by kottenator** [comment]
@tekbahadur1996 - do you have upload progress events? If you're using JS File API - you should to. And if you do - I'd recommend to update the circle value _honestly_, according to the file upload progress:

```js
yourFileUpload.on('progress', percentage => {
  circle.circleProgress('value', percentage / 100);
});
```

**Comment by tekbahadur1996** [comment]
```js
xhr: function() {
  var xhr = new XMLHttpRequest();
  xhr.upload.addEventListener('progress', function(evt) {
    if (evt.lengthComputable) {
      // Calculate the percentage of upload completed.
      var percentComplete = evt.loaded / evt.total;
      percentComplete = parseInt(percentComplete * 100);

      // Update the Bootstrap progress bar with the new percentage.
      console.log(percentComplete)
      $('#circle').circleProgress('value', percentComplete);

      // Once the upload reaches 100%, set the progress bar text to done.
      if (percentComplete === 100) {
                                
      }
    }
  }, false);

  return xhr;
}
```

I am using AJAX request. Please help me out.

**Comment by kottenator** [comment]
You've missed `percentage / 100` from my example above. Please, change:

```js
var complete = evt.loaded / evt.total;
console.log(Math.round(complete * 100) + '%');
$('#circle').circleProgress('value', complete);
if (complete === 1) {
  // Do your logic                              
}
```

**Comment by kottenator** [comment]
@tekbahadur1996 - I hope I've helped you. I'm closing this ticket, but feel free to reopen.
