### ISSUE TITLE
Any way to display increasing percentages inside the circle?

### ISSUE THREAD

**Issue by kakariko-village** [kottenator/jquery-circle-progress#179]
Hi is there anyway to add an increasing percentages inside the circle? E.g: 0% increasing to 100% and sync with the animation of the circle?

**Comment by kottenator** [comment]
Hi, @kakariko-village!

Sure there's a way, e.g. look into #20. Or there's an example [at this page](http://kottenator.github.io/jquery-circle-progress/).

**Comment by kakariko-village** [comment]
Any way to reset the process bar to 0 immediately when it reach 100 and stop animation at this point?

**Comment by kottenator** [comment]
Yes, I think so:

```js
$('.circle').circleProgress({value: 1}).one('circle-animation-end', function() {
  $(this).circleProgress({value: 0});
});
```

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.
