### ISSUE TITLE
Draw the progress bar around a circular image

### ISSUE THREAD

**Issue by IngwiePhoenix** [kottenator/jquery-circle-progress#18]
Hey.

I am using Twitter Bootstrap 3.2 which offers a class that turns an image into a circular view. Its not cropped or anything - but it just is styled to look like its actually round.

For my app, I'd like to draw a progress bar around such image. To be specific: I am uploading an image, and I want to show the image preview and have the progress bar surround it. This way I dont need to make extra space for a usual progress bar and can keep the content displayed minimal.

Is that possible with this plugin?

Kind regards, Ingwie

**Comment by kottenator** [comment]
Yes, it's possible. Here is an [example](http://jsbin.com/pofobe/1). 

I'm going to implement more friendly way to use my plugin as a progress bar in the next version.

**Comment by IngwiePhoenix** [comment]
Awesome!

For what purpose is

	<div id="progress"></div>

though? I understand everything else though. :)

**Comment by kottenator** [comment]
It's redundant, I forgot to remove it :)

**Comment by IngwiePhoenix** [comment]
I see. :) Thanks for the demo, I am going to put your plugin in my project then so i wont forget to update it.
