### ISSUE TITLE
Change fill color after initialization

### ISSUE THREAD

**Issue by php-it** [kottenator/jquery-circle-progress#184]
First of all, thank you for this nice plugin!

Right now, I'm trying to change the value and color after a circle has initialized. This is my code:

```javascript
var circle = $('.circle').circleProgress({
    value: 0.80,
    fill: 'orange'
});
	
setTimeout(function() {
    circle.circleProgress('value', 0.50);
    circle.circleProgress('fill', 'green');
},3000);
```
I want this to change the progress bar from 80 to 50 percent and set the fill color to green after a few seconds. The progress changes smoothly to 50 percent, but the color won't change. Am I doing something wrong here?

Thanks in advance!

**Comment by lbelavoir** [comment]
Apparently you can't change `fill` without putting it in an object.
In your case I'll suggest something like this if you want to wait the end of your animation:

```
setTimeout(function() {
  var colorChanged = false;
  circle
    .on("circle-animation-end", function() {
      if (!colorChanged) {
        colorChanged = true;
        circle.circleProgress({
          animationStartValue: 0.5,
          value: 0.5,
          fill: "green"
        });
      }
    })
    .circleProgress("value", 0.5);
}, 3000);
```

**Comment by php-it** [comment]
Thank you @lbelavoir as this does the job! This issue can be closed.
