### ISSUE TITLE
Issue with progress

### ISSUE THREAD

**Issue by danstanhope** [kottenator/jquery-circle-progress#20]
Hey,

Great plug-in. 

Just an issue with the progress...it always goes to 100% rather than the value specified. Not sure if this is the intended functionality, but I'd expect progress to stop at the value specified. In this case 75%

$('.second.circle').circleProgress({
    value: 0.75
}).on('circle-animation-progress', function(event, progress) {
    $(this).find('strong').html(parseInt(100 * progress) + '<i>%</i>');
});

Thanks!

**Comment by kottenator** [comment]
Thanks for the nice words!

About your request - it's already implemented. Try next:
```js
$('.second.circle').circleProgress({
    value: 0.75
}).on('circle-animation-progress', function(event, progress, stepValue) {
    $(this).find('strong').html(parseInt(100 * stepValue) + '%');
});
```

**Comment by danstanhope** [comment]
Hey!

I was just about to reply…I noticed the stepValue in another example :)

Great work!

Take care,
Dan

**Comment by gomesNazareth** [comment]
Had the same issue . The below fixed the problem

` jQuery(classname).circleProgress({
            value: val,
            thickness:3,
            fill: {
                gradient: ["#000", "#f1f1f1"]
            }
        }).on('circle-animation-progress', function(event, progress,stepValue) {
            jQuery(this).find('strong').html(Math.round(100 * stepValue) + '<i>%</i>');
        });
`
