### ISSUE TITLE
Drawing circle at the start of the arc

### ISSUE THREAD

**Issue by pineapple-thief** [kottenator/jquery-circle-progress#21]
I would like to do something like this using your plugin, basically just to draw circle of certain radius at the start of the arc.
![untitled-1](https://cloud.githubusercontent.com/assets/4012690/6435216/17aceba6-c0e4-11e4-8494-e9aa1515f448.png)
Is it possible with your plugin? I've browsed source code, but I'm unsure where to put this kind of stuff, my guess is that I add extra method like drawStartCircle in drawArc function and extra property for startCircleRadius in the prototype. Would do you think?

**Comment by pineapple-thief** [comment]
Ok, I've implemented this, but in a pretty hacky way. I had to increase canvas height by circleRadius and add it to y coordinate in arc calls in drawArc, drawEmptyArc functions. It works for me, but I have suspicion I've broke something elsewhere, like image fill or something like that. Maybe you would add this as a feature in next release?

**Comment by kottenator** [comment]
Hi!

First of all, thank you for using my circles! ;)

As I understand, the difference between your and default behaviour that you have a big dot at the beginning. IMO this is not very popular behaviour so I have doubts about adding it to the standard options.

However, I have made a snippet for you, that implements correct work with all types of fillings and other options. You may [find it here](http://jsbin.com/bivowi/2).

**Comment by pineapple-thief** [comment]
I thank you for your snippet, my way of doing it was more crude)

2015-03-08 9:42 GMT+10:00 Rostyslav Bryzgunov <notifications@github.com>:

**Comment by muhammadadamfirdaus** [comment]
Hello, how if I'd like put the dot on the end?

Thanks before.
