### ISSUE TITLE
Can you stack circles?

### ISSUE THREAD

**Issue by hmaidasani** [kottenator/jquery-circle-progress#22]
I built this tool http://hmaidasani.github.io/RadialChartImageGenerator/ using jquery.knob to generate images from the canvas for apple watch assets. Do you think it's possible with jquery-circle-progress? I am consider switching to using your tool since it has animation support.

**Comment by kottenator** [comment]
Hi!

Thank you for your interest in my tool.

My tool is very simple and flexible so you can do many interesting things with it :)

Here is [my snippet](http://jsbin.com/zepabe/1) with nested circles. Is that what you are looking for?

**Comment by kottenator** [comment]
I hope that I've answered to your question. I'm closing the ticket now
