### ISSUE TITLE
Is it possible to control the empty fill thickness?

### ISSUE THREAD

**Issue by janhartmann** [kottenator/jquery-circle-progress#24]
I am trying to get the empty fill thickness a bit smaller than the fill thickness - is there an elegant solution to this?

And also, this library is the king!

**Comment by kottenator** [comment]
Thanks for good words!

Unfortunately it's not so easy now, but it's possible. Here, I've made [a snippet](http://jsbin.com/jeranu/1/).

**Comment by kottenator** [comment]
But this is a good feature request for the future version. I will implement it

**Comment by janhartmann** [comment]
Super cool, thanks a lot - keep coding! ;-)

**Comment by kottenator** [comment]
I will, just need to get few evenings for this :)

**Comment by kinzania** [comment]
Amazing ...

but I have a little problem,
This can be made for the countdown?
I had a problem with setInterval,

I hope the result is the value of your plugin is updated every second.
but it did not succeed.

see this [example,](http://codepen.io/anon/pen/qbeJWx)
Can you provide a solution?

**Comment by kottenator** [comment]
@kinzania - [here](https://codepen.io/anon/pen/WELNag) I've updated your example

**Comment by kinzania** [comment]
Wow you are really the best.

yesterday I have tried in my own way (before you reply to my message).

and this is the [result](http://codepen.io/kinzania/pen/oxvVjV).

Do you want to help how to synchronize plugin value jquery-circle-progress with [jQuery countdown](http://hilios.github.io/jQuery.countdown/)

I was glad once with your response so quickly.

thank you

**Comment by AbhaySoningra** [comment]
Hey Any update on this request to control thickness of the empty Fill ? 
Also any way to change the center blank color ?

**Comment by kottenator** [comment]
@AbhaySoningra - not yet, sorry.

**Comment by AbhaySoningra** [comment]
No Worries Mate, anyway Thanks for this wonderful Library :)
