### ISSUE TITLE
Problem with the progress

### ISSUE THREAD

**Issue by JillzTom** [kottenator/jquery-circle-progress#25]
I tried to use the following code for the progress. But when the value is 100%, it only shows 00. But the circles is complete. What might be the problem?
```
$('.second.circle').circleProgress({
    value: 0.75
}).on('circle-animation-progress', function(event, progress, stepValue) {
    $(this).find('strong').html(parseInt(100 * stepValue) + '%');
});
```

**Comment by kottenator** [comment]
Could you, please, provide the full example? E.g. on jsbin.com

**Comment by JillzTom** [comment]
How can I link the 'jquery-circle-progress' in jsbin?

**Comment by kottenator** [comment]
Here is my [recent jsbin](http://jsbin.com/jeranu/1/)

**Comment by JillzTom** [comment]
Okay, here is it: http://jsbin.com/pugefowaga/1/

**Comment by kottenator** [comment]
Here, I've [fixed your jsbin](http://jsbin.com/kumibusaji/1/). The problem was in your code: `String(stepValue.to fixed(2)).substr(2)` it's getting only 2 last digits and cutting the third one (in case of 100)
