### ISSUE TITLE
Show 100% in Value Progress

### ISSUE THREAD

**Issue by modxuser** [kottenator/jquery-circle-progress#28]
I'm not sure if this is the right place to post this but here goes anyway.

I'm not a javascripter and have no tech knowledge.

Question 1:
I'm trying to get the Value progress to show 100%

If I add "value: 1.0" - the value displayed is ".00"
If I add "value: 100" - the value displayed is "00.00"

How do I get a displayed value of "100" ?

Question 2:
The value in the front end shows a dot before the number - can this be removed

Example:
If I add "value: 0.50" - the value displayed is ".50"

Question 3:
Is it possible to group settings instead of having to create settings for each circle - I have 4, the only setting that changes is the value - 25, 50, 75, 100

Any help is much appreciated.

**Comment by modxuser** [comment]
My call is:

$('.circle.nr4').circleProgress({
	animationStartValue: 1.0,
	value: 1.0,
	size: 200,
	emptyFill: "rgba(255,255,255,.1)",
	fill: {
		color: '#FF0000'
	},
	thickness: 20,
}).on('circle-animation-progress', function(event, progress, stepValue) {
	$(this).find('i').text(String(stepValue.toFixed(2) + '%').substr(1));
});

**Comment by modxuser** [comment]
have moved over to: https://github.com/rendro/easy-pie-chart

their solution works how I need it to

**Comment by kottenator** [comment]
I'm sorry, I had no chance to answer earlier. Have you solved your problem by yourself or do you need help?

**Comment by kottenator** [comment]
Oh, I see. Well, it's your choice. 

As for 100% - you were parsing percentage number in a wrong way. You shouldn't use `n.toFixed(2).substr(1)`, it returns first 2 digits of the fraction part. You should use `parseInt(100 * n)` instead.

Here is the full example (and [demo](http://jsbin.com/hoxivirubi/1)):

```js
$('.circle').circleProgress({
    value: 1,
}).on('circle-animation-progress', function(event, progress, stepValue) {
    $(this).find('strong').text(parseInt(stepValue * 100));
});
```

**Comment by modxuser** [comment]
@kottenator

I have moved to a different script as it does what I need out of the box.

I searched the net and with the help of some posts I found I tried modifying your script but I am not a tech when it comes to JS - didn't work out.

The only problem I had left over was showing "100%" in the front-end

This was very helpful - http://jsfiddle.net/edward_lee/1f58u1o5/2/

**Comment by modxuser** [comment]
Just modified my code that I had - works perfectly with your changes - thanks.

I now have 2 solutions :)

**Comment by kottenator** [comment]
You're welcome! I'm always glad to help
