### ISSUE TITLE
Request for the ability to animate to a new value

### ISSUE THREAD

**Issue by nickludlam** [kottenator/jquery-circle-progress#29]
I love the library, but I really want to be able to change the current position of the progress bar via an ajax method. Is there any way to do this without redrawing the whole bar from zero, and without needing to cache the previous position it used outside of the widget itself?

**Comment by kottenator** [comment]
Actually you're not the first who needs this functionality... I guess the time has came to release a new version of the library :)

**Comment by kottenator** [comment]
Sorry, I had crashed my old laptop, was super busy on my new job and with my little kid... But finally I've implemented your request.

Version `1.1.3` has been released and it contains dynamic value update functionality.

**Comment by nickludlam** [comment]
Oh thats fantastic, thanks for letting me know!
