### ISSUE TITLE
iphone mobile    edge very vague

### ISSUE THREAD

**Issue by qdsang** [kottenator/jquery-circle-progress#30]
![image](https://cloud.githubusercontent.com/assets/804455/7607636/8947d64c-f995-11e4-8afe-20d542282628.png)

**Comment by kottenator** [comment]
Maybe [my suggestion](https://github.com/kottenator/jquery-circle-progress/issues/17) could help

**Comment by kottenator** [comment]
I know it's not the perfect solution, but it works. 
I will keep your request in mind for future to implement automatic pixel-ratio detection (maybe using [this](http://stackoverflow.com/questions/4720262/canvas-drawing-and-retina-display-doable))
But I'm resolving the issue for now.
