### ISSUE TITLE
Value changing during drawing

### ISSUE THREAD

**Issue by olezya** [kottenator/jquery-circle-progress#34]
Hello
Thanx for plugin. It's great, but I'd like to know can you make event that change a value when line drawing?
as this http://www.jqueryscript.net/demo/Simple-jQuery-Circular-Loading-Bar-with-Percentage-Rotator/

Thanx

**Comment by kottenator** [comment]
Wait, I already have this event - `circle-animation-progress`. You may see it in action on the [project demo-page](http://kottenator.github.io/jquery-circle-progress/). Take a look at [the snippet](http://jsbin.com/gijeba/1/edit?html,js,output) to see the code

**Comment by olezya** [comment]
thank you for reply
nice thing

2015-05-26 23:44 GMT+03:00 Rostyslav Bryzgunov <notifications@github.com>:

**Comment by kottenator** [comment]
I guess I may close this issue

**Comment by qwer4k** [comment]
#161 here's the issue.
