### ISSUE TITLE
Circle color attribute + IE8 support.

### ISSUE THREAD

**Issue by TomThak** [kottenator/jquery-circle-progress#35]
It would be nice to have circle color attribute. Now it is somehow grey color, which seems to have some opacity. It would be nice to be able to definie your own color. For example I would like to have light red color of the whole circle and the progress will have dark red color. Now everything has to be in grey (due to page background).

Another thing is IE8 support. It would be nice to somehow have IE8 support.
it is still heavily used on WIN XP.

**Comment by pangolingo** [comment]
I was able to get these working on IE8 using ES5 Shim (to fill in missing JS methods) https://github.com/es-shims/es5-shim and ExplorerCanvas (to get Canvas working) https://github.com/arv/ExplorerCanvas
It's possible that complex fills won't work, but solid colors definitely do.

**Comment by TomThak** [comment]
Thanks! I will try it. It is not so important for me to have there the animation, but I need to have the page without js errors and this cause an JS error of undefined method for object in IE8. 
The best result for me will be if it will display my numbers, texts and circle even without animation for IE8, so there will be the data without error. Animation is an advantage for new browsers.

**Comment by kottenator** [comment]
You can set "background circle" color using `emptyFill` config option. By default it's transparent gray - `rgba(0, 0, 0, .1)`, but you may set it to red if you want to - `#ff0000`

As for IE8 support - I have not implemented it because it requires extra effort and would make my code "dirty". You may try to use some IE8 `<canvas>` polyfill... I will try it and let you know if it works

**Comment by kottenator** [comment]
I've tried to use `excanvas`. You may take a look at [my example](http://jsbin.com/qegoto/1/). I've met a problem - `excanvas` doesn't want to stroke the circle with gradient fill so I used solid fill fallback.

I don't want to struggle with IE8, I want people to stop using it instead :) But you may dig into my example and use it in your code

**Comment by TomThak** [comment]
I understand, that you would like people to use better browsers, We also want it, but We cannot somehow force our clients to sell their computers and buy new ones with Win Vista + newer, because They have Win XP in their offices with IE8 and due to google analytics We can see, that there are many customers, who still use IE8. MS should block the Win XP :D

I will try your example. Thanks!

**Comment by kotmatpockuh** [comment]
@TomThak @kottenator   how did you add thousandth value in your counter?
