### ISSUE TITLE
start animation when the section is active

### ISSUE THREAD

**Issue by MahmudSajib** [kottenator/jquery-circle-progress#36]
hi,is it possible to start animation when the containing section is active..currently it finishes animation before i go to my section..

**Comment by kottenator** [comment]
If you want to start the animation when you scroll to the element - [this might be the solution](https://github.com/kottenator/jquery-circle-progress/issues/8)

If you want to start the animation when you dynamically show/hide the element - you should manually trigger "redraw" on element appearance

**Comment by MahmudSajib** [comment]
Hi,Thanks for your reply..One request..Please include this process on the
documentaition so that the new learners will get the utmost benefit..

**Comment by kottenator** [comment]
Yes, that's a good point, will do (as soon as I will have some time...)

**Comment by MahmudSajib** [comment]
Once again thanks for your reply & such a outstanding plugin..love from
Bangladesh.

**Comment by kottenator** [comment]
Nice to hear that, thanks! ;) I'm going to improve it soon and to resolve all the issues
