### ISSUE TITLE
Text in center of progress bar

### ISSUE THREAD

**Issue by gaz492** [kottenator/jquery-circle-progress#39]
How would you go about making the text in the center of the progress bar to stay at the center of the progress bar on a responsive website?

**Comment by kottenator** [comment]
You gave me a challenge here :) I tried to solve it using CSS but I failed (maybe it's still possible, though). So [here is my solution using canvas](http://jsbin.com/gabeli/4)

**Comment by gaz492** [comment]
Just what i was looking for cheers :)

**Comment by kottenator** [comment]
This request is related to [flexible-width issue](https://github.com/kottenator/jquery-circle-progress/issues/39) (just to link them)

**Comment by NoobTW** [comment]
When redraw with different text, the texts overlap.

**Comment by vivek28111992** [comment]
I am not able to write text in center

**Comment by kottenator** [comment]
Please, create a snippet on jsbin.com (e.g.) and provides a link here
