### ISSUE TITLE
How to custom the final value (instead of percentages)?

### ISSUE THREAD

**Issue by czmarcos** [kottenator/jquery-circle-progress#40]
Is it possible to change the final number to a custom value (instead of 100%) ?

For example, create a circle that increases to a final value of "7,500" (with an animated increasing values to a full circle).

**Comment by kottenator** [comment]
Sure, you can do this:

```js
var circle = $('#circle').circleProgress({
  value: 1
});

circle.on('circle-animation-progress', function(e, p, v) {
  $(this).find('strong').text((7500 * v).toFixed(0));
});
```

**Comment by kottenator** [comment]
I'd close the issue if you don't mind ;)
