### ISSUE TITLE
Possible to redraw from previous value?

### ISSUE THREAD

**Issue by spandadk** [kottenator/jquery-circle-progress#41]
Very good job with the library! Fits a little project of mine totally perfect.

I have two questions:

1. Lets say i've initiated the circle and it ends up on value 0.75.
Now I click a button and then want to redraw the same circle from value 0.75 (and not start over from 0 again). Is this possible?

2. At the same time I want to redraw the color in the circle - preferable some way so its not a hard cut, but so it fades over to the new color. Is this possible?

Cheers!

**Comment by kottenator** [comment]
Thank you for warm words!

Sure, all is possible:

```js
var circle = $('#circle').circleProgress({ value: 0.75 });

// update the value
setTimeout(function() {
    circle.circleProgress('value', 1)
}, 2000);

// bind smooth color change
circle.on('circle-animation-progress', function(e, p, v) {
  var r = parseInt((1 - v) * 255 + v * 60),
      g = parseInt((1 - v) * 31 + v * 255),
      b = parseInt((1 - v) * 65 + v * 150);

  var instance = $(this).data('circle-progress');
  
  instance.fill = {
    color: 'rgb(' + r + ', ' + g + ', ' + b + ')'
  };
  
  instance.initFill(); // this is required to apply new fill;
                       // sorry, it's not so common request
});
```

**Comment by kottenator** [comment]
I think we're done here. I'm closing the issue
