### ISSUE TITLE
real Progress

### ISSUE THREAD

**Issue by celevra** [kottenator/jquery-circle-progress#42]
Hi,

i've got an uploader and i want to display the progress, so i'm updating the progressCircle every percent change.

If i simply update the value it starts from the beginning every time i update, so i set animationStartValue before, like that:

```
        $('#circle').circleProgress({ animationStartValue:  progress});
        $('#circle').circleProgress({ value:  newProgress});
```

but is that really the way to go? 
Because if i do so, and the value changes fast there is no animation...

regards and thank you for your work!

celevra

ps.: can you tell me the color codes from the blue circle (the third) in the readme?

**Comment by kottenator** [comment]
Hi!

Yes, I've recently implemented value update that you need:

```js
el.circleProgress('value', newValue);
```

And it handles unfinished animation.

Blue gradient: I'm not 100% sure but try this one:

```js
['#0681c4', '#4ac5f8']
```

**Comment by celevra** [comment]
Hi,

thanks for the fast answer.
this sounds good, unfortunately it doesn't work as expected the animation starts with the last update. 
i'm not sure how i should explain it but you can go to https://socket.lionkeen.net open it in two windows, select an image (best one round about a few megabytes), open the console and see the percentage flow but no animation, only at the end the circle will fill.

regards

celevra

ps. the gradient is exactly what i was searching for

**Comment by kottenator** [comment]
Now I understand the problem. Currently I'm just pausing the animation on the current state and start new animation from that point. And so on, so if you update value pretty frequently, it will not show smooth dynamics, it will jump to the last value. I have some ideas, but it's not so easy. But I will handle that, no worries ;)

**Comment by celevra** [comment]
sounds promising, i'm curious and here for test! :-)

**Comment by kottenator** [comment]
There are 2 _simple choices_:
- `animation.stop(true, false)` - what I do now: stop previous animation on its _current state_, jump to the next one
- `animation.stop(true, true)` - [the "ugly" one](http://jsbin.com/pofobe/6/edit?js,output): stop previous animation on its _final state_, jump to the next one; itugly

**Comment by kottenator** [comment]
Ok, I figured out that it's hard to "tweak" jQuery running animation.
But here is [my workaround](http://jsbin.com/pofobe/8). Does it work for you?

**Comment by celevra** [comment]
jep it looks smoother, not perfect but absolutely useable, thank you very much for your work!

**Comment by kottenator** [comment]
I understand that it's not actually the problem fix... but I will resolve this issue for now :)
