### ISSUE TITLE
Duration doesn't seem to have an affect?

### ISSUE THREAD

**Issue by stevenkaza** [kottenator/jquery-circle-progress#45]
Thanks for creating this, its very cool, just a question about duration and how I am using it:

  function createCircle(circleID){
       $(circleID).circleProgress({
         value: 1,
         size: 25,
        animate:{
         duration:[ 2000],
           },
         fill: {
             gradient: ["blue"]
         }
     });
}
Regardless of what number I put for duration, the speed of the circle being drawn always seems to be the same. Am I doing something wrong? Perhaps I should put duration:["slow"] or something like that?
Steve

**Comment by kottenator** [comment]
np, I would make it a plain property (as you initially wrote) if it wouldn't be a part of jQuery animation config
