### ISSUE TITLE
Is posible "event click on thickness" ?

### ISSUE THREAD

**Issue by nhattuanbl** [kottenator/jquery-circle-progress#46]
Is posible "event click on thickness" to set/get new value ?

**Comment by kottenator** [comment]
Hi! Let me think about it...

**Comment by nhattuanbl** [comment]
Hi, thank for support, im making something like music progress bar 
![untitled](https://cloud.githubusercontent.com/assets/7424019/9184274/7a02e9b2-3fde-11e5-8fb6-ce3ed48cef78.png), if this posible it will very cool :D

**Comment by kottenator** [comment]
Looks nice! I will find a solution, soon...

**Comment by kottenator** [comment]
Sorry for delay, this feature was not so easy to implement but I've done it! [Here is my implementation](http://jsbin.com/fetequ/3). I'm closing this ticket for now. But if you'll meet problems - you can reopen it
