### ISSUE TITLE
Can't get the value change to animate

### ISSUE THREAD

**Issue by CaptainMcMarcus** [kottenator/jquery-circle-progress#47]
Hello, this is a fantastic plugin that you've made and is exactly what I've been looking for :+1: 

The only problem is that for some reason I can't get it to animate when I update the value. The whole thing just disappears entirely.

I'm trying to use it as a download meter to show the user the total percentage of the number of files they are downloading.

This has been what i've been trying to use and every time I update it with the new value the whole thing just vanishes
```
iDifference = Math.round(iFilesTotal - iFilesNeeded);
progress = (iDifference / iFilesTotal).toFixed(2);
$( "#circle" ).circleProgress( 'value', progress );
```

I've had to resort to what you mentioned in an earlier issue topic and this is my current set-up where I can successfully update the percentage value of the circle but it doesn't animate to the updated value :(
(I've cut the code down that I have to make it easier to read but the gist of it is when a file has finished being downloaded it does the maths and then fires of the UpdateCircle function)
```
iDifference = Math.round(iFilesTotal - iFilesNeeded);
progress = (iDifference / iFilesTotal).toFixed(2);
			
UpdateCircle();

var circle = $('#circle').circleProgress();
	function UpdateCircle() {
	circle.circleProgress({
	animationStartValue: circle.data('circle-progress').value,
		value: progress
	});
};
```

I've probably done something wrong somewhere and it's probably a total noob error but I would greatly appreciate your help :)

**Comment by kottenator** [comment]
Hi! Thank you for a compliment, I'm doing my best :)
Here is [an example of how it may be done|http://jsbin.com/napebo/2]

**Comment by CaptainMcMarcus** [comment]
Thanks for your super speedy reply, It turns out that I had some dodgy code and I was updating it too frequently which is why it wasn't animated.

Sorry I came here with a noob question xD

But anyway, well done, you've made a super awesome script and I'm loving it ^_^

**Comment by kottenator** [comment]
Thanks!
