### ISSUE TITLE
How to show percentage progress?

### ISSUE THREAD

**Issue by singhketan** [kottenator/jquery-circle-progress#48]
I am using something like this:
  $('#progress_container').circleProgress({
              value: 0.2,
              startAngle: -Math.PI/2,
              fill : {
                  color: '#FBC70D'
              },
              thickness: '2'
          }).on('circle-animation-progress', function(event, progress) {
              $(this).find('strong').html(parseInt(100 * progress) + '<i>%</i>');
          });

But the percentage doesn't show up, only the circle. Am I missing anything? Do I need to set up any html as well? Please response ASAP.

**Comment by kottenator** [comment]
You may [find the solution in this ticket](https://github.com/kottenator/jquery-circle-progress/issues/34)

**Comment by kottenator** [comment]
The code snippet I provided in that ticket should work for you. I'm resolving the issue
