### ISSUE TITLE
Start circle, where previous ended

### ISSUE THREAD

**Issue by rowild** [kottenator/jquery-circle-progress#5]
Hi, this is not a bug report, but a question, hoping you could help me :-)

I'd like to have 3 circles next to each other, the first animating to position x, the second to pos y and the third to position z. It would be very nice if circle 2 could start at that position, where circle one ended. How do I have to calculate that? ...sorry, my Math is really baaaaaad :-(

$('#circle_01').circleProgress({ value: 0.104 });
$('#circle_02').circleProgress({ value: 0.32, startAngle: ???[end position of circle one]  });
$('#circle_02').circleProgress({ value: 0.516, startAngle: ???[end position of circle two]  });

Thanks so much!

**Comment by skiokko** [comment]
Hi,
Very great plugin, the only small and good i found on web. Im in truble to set angle. I want start to 0° so start from top center, but not able to found the formula.
If you have time tell me thanks!
Federico

**Comment by kottenator** [comment]
Hi! Thanks! Try next configuration option: `startAngle: -Math.PI / 2`

**Comment by skiokko** [comment]
Thank you work perfectly!

**Comment by markocrni** [comment]
I had the same problem with start angle as @skiokko 
Can you add to documentation what is the value (type of value) that receives this parameter.
Wouldn't it be logical that this parameter indicates in degrees?!

**Comment by kottenator** [comment]
@markocrni: in JavaScript world (as well as in Java, Python, etc), usually angles are measured in _radians_, not _degrees_. I didn't mention this because I thought it's obvious.

BTW, in documentation I have this: `startAngle` defaults: `-Math.PI`, which is `-1.570796...`, not `-180`, if you'll do `console.log()`.
