### ISSUE TITLE
Hook into multiple progress callbacks

### ISSUE THREAD

**Issue by simonmacfadyen** [kottenator/jquery-circle-progress#50]
Hey, 

I'm trying to hook into multiple 'circle-animation-progress' instances, as per below. I can't seem to get anywhere with the circle-animation-progress, as it always will update my percentage value for both.

      	var percentage = '';
      	var circle = [];
      	$(".circle-stat .circle").each(function(i, val) {
      		percentage = $('.percentage_value', val).val() * 100;
      		console.log(percentage);
			circle[i] = $(val).circleProgress({
				lineCap: 'round',
				fill: { gradient: ['#71d4fc', '#05a1e0'] }
			}).on('circle-animation-progress', function(event, progress) {
				circle[i].find('p.percentage').html(parseInt(percentage * progress) + '<i>%</i>');
			});
      	});

My markup is the following, 

<div
	class="circle"
	data-value="<?php echo $circle_percentage_end_value; ?>"
	data-size="180"
	data-thickness="8"
	data-animation-start-value="<?php echo $circle_percentage_start_value ?>"
	data-reverse="false">
	<p class="percentage"></p>
	<input class="percentage_value" type="hidden" value="<?php echo $circle_percentage_end_value; ?>">
</div>

Is this a bug or a scope issue? Any ideas really appreciated.

-- Simon

**Comment by kottenator** [comment]
Hi!

Here I've made a [demo that should help you](http://jsbin.com/facoko/2)

**Comment by kottenator** [comment]
*UPD:* I've updated the demo link in my comment above

**Comment by simonmacfadyen** [comment]
Hey there, thanks so much the demo!

That's cool, I must of been really close as I got it working before I read this. I'll look at your solution and make sure i'm not doing anything funky.

Nice plugin, btw!
