### ISSUE TITLE
angular js binding problem

### ISSUE THREAD

**Issue by jeffryang24** [kottenator/jquery-circle-progress#51]
Thanks for your great plugin before. I just used it with angularjs and requirejs, it worked fine if I added static value inside ```data-value``` attribute. But, when I added my controller scope variable, for example \:

**myController.js**
...

```fidi.Quota = 0.8```

...

In the html directive,
```<div id="fidiTargetQuota" data-value="{{fidi.Quota}}">
    ...            
    </div>```

The progress bar did not show up. But, the sources showed that the data-value already binded with value ```0.8```.

Thanks! Sorry for my bad English.... :)

**Comment by kottenator** [comment]
Sorry, I'm not AngularJS expert... Could you create a working code demo (on jsbin.com, codepen.io or other service) so I could view & edit it?

**Comment by jeffryang24** [comment]
Sorry, it was my mistake. I already do a research on this problem and the root of this problem is the angular ui router. Sorry... My bad....

**Comment by jeffryang24** [comment]
Btw, thank you for your plugin!!! :)

**Comment by kottenator** [comment]
You're welcome! And your English is very good! ;)
