### ISSUE TITLE
Labels and gradient customization

### ISSUE THREAD

**Issue by dkroondijk** [kottenator/jquery-circle-progress#52]
Hi, just have a couple of quick questions. I've been struggling to implement the following customizations.

* How do you change the gradient such that the second color is the end color of the circle? (ie. there would be a hard transition between the end and start color instead of fading back into the start color)
* How do I add a label/image to the end value of the progress bar?

I've added the image below for illustration.

<img width="255" alt="screen shot 2015-09-17 at 3 44 34 pm" src="https://cloud.githubusercontent.com/assets/9505970/9948007/083d315a-5d54-11e5-87aa-65d6409980c1.png">

Any help would be much appreciated!

**Comment by kottenator** [comment]
Hi! I will crete a snippet for you on this weekend (sorry, can't do this right now)

**Comment by dkroondijk** [comment]
Wow, thanks for the quick reply and thanks for your help, much appreciated! Great plugin btw!

**Comment by kottenator** [comment]
[Here is my snippet](http://jsbin.com/pidubi/6/edit?html,css,js,output).

Answering to your questions:

- you're looking for _conical asymmetric gradient_ which is not available for `<canvas>` yet. But there is a way to make it - using _image fill_ (that's what I do in my snippet)
- adding a label to the _arc end point_ is a bit tricky - you have to calculate coordinates by yourself (see my snippet code)

**Comment by dkroondijk** [comment]
That's perfect! Thanks again so much for your help and your time.

**Comment by kottenator** [comment]
Here is an [updated version of the snippet](http://output.jsbin.com/pidubi/7) that also _animates the value_.

**Comment by PowerfulPaw** [comment]
How to create this background square like in your examples?

**Comment by kottenator** [comment]
@PowerfulPaw : I didn't quite get you - what square?

**Comment by PowerfulPaw** [comment]
http://i.imgur.com/seDoWGK.png

**Comment by kottenator** [comment]
Oh, I see. That's a _conical gradient_ - you can create it in many graphical editors (Photoshop, GIMP, etc). Sorry, I haven't found a good tutorial, but I'm sure, you'll handle it ;)

**Comment by PowerfulPaw** [comment]
Thanks for answer, I thought I could make it with CSS.

**Comment by kottenator** [comment]
Unfortunately, it's only in CSS4 draft yet :(
