### ISSUE TITLE
help

### ISSUE THREAD

**Issue by coolara** [kottenator/jquery-circle-progress#53]
this plugin has a problem when i try to use the property of  animationStartValue  for the first time.
The first time , i use this plugin , and i set a value to the animationStartValue property , it doesn't work

**Comment by kottenator** [comment]
Hi!

[Here is an example](http://jsbin.com/taduse/2/edit?js,output), `animationStartValue` works fine at the first time. Or have I misunderstood you?

**Comment by kottenator** [comment]
@coolara - has it solved your problem?

**Comment by coolara** [comment]
not yet. the problem still exists

**Comment by kottenator** [comment]
Do you have this problem with my demo? Can you give me a code example of the problem?

**Comment by coolara** [comment]
$.rotate({value: 0.8, time: 3,animationStartValue: 0.2});
                $.rotate = function (obj) {
                    var rotate = $("<div class='bg'></div>"
                        + "<div id='circle'>"
                        + "</div>");
                    $("#rotate").append(rotate);
                    $('#circle').circleProgress({
                        value: obj.value,
                        size: 250,
                        fill: {
                            gradient: ["#5DC0FF", "#A5D0DC"]
                        },
                        emptyFill: "rgba(250, 250, 250, .1)",
                        startAngle: -Math.PI / 2,
                        thickness: 10, 
                        lineCap: "round",
                   
                        animation: {
                            duration: obj.time * 1000
                        },
                        animationStartValue: obj.animationStartValue
                    });
                }

**Comment by coolara** [comment]
second do this funciton
![qq 20151003103753](https://cloud.githubusercontent.com/assets/14053077/10261124/d7a1ce98-69ba-11e5-8a69-d4aec80c8dcd.png)
first do this function
![qq 20151003103656](https://cloud.githubusercontent.com/assets/14053077/10261119/b65446da-69ba-11e5-8441-20b1535a226b.png)

**Comment by kottenator** [comment]
According to your code:
- each time you call `$.rotate(...)` - you insert new `<div id="circle">` into `<div id="rotate">`
- then you do `$("#circle").circleProgress(...)`. 
- jQuery finds _not the newly inserted_ `<div id="circle">` _but the "old" one (the first one)_

This is probably not what you want and the reason of your problem.

I don't 100% understand what you're trying to do, so I give you two solutions:
1. If you want to create a circle each time you call `$.rotate(...)` - [solution 1](http://jsbin.com/joqeji/2/edit?js,output)
2. If you want to re-use the same circle and just to restart its animation when you call `$.rotate(...)` - [solution 2](http://jsbin.com/yajaji/2/edit?js,output)

**Comment by coolara** [comment]
thank you for solving  my problem ，it runs correctly
