### ISSUE TITLE
Four Different Colours without Gradient and Image

### ISSUE THREAD

**Issue by gthapar** [kottenator/jquery-circle-progress#54]
Hello,

Is it possible to add four different colours with or without gradient effect?

![screen shot 2015-10-03 at 10 38 20 pm](https://cloud.githubusercontent.com/assets/4481867/10264035/84bb7dfe-6a1f-11e5-8ed1-07ac3f7391cf.png)

I actually want the colours to appear one after another and not repeat. Not like the above image.

**Comment by kottenator** [comment]
The answer is - yes, of course :) [Here is my demo](http://jsbin.com/weqemo/2/edit?js,output)

**Comment by gthapar** [comment]
Thanks! But I was actually looking to add colours dynamically. I won't be able to use an image. :(

Any other way to achieve the 4th one in the demo? May be add support for array of colour similar to gradient?

**Comment by kottenator** [comment]
Oh, that's a bit tricky but possible. [Here is my solution](http://jsbin.com/qarefi/2/edit?js,output)

**Comment by gthapar** [comment]
Awesome, thanks a lot! But please seriously consider the idea of supporting colour array for adding multiple colours just in case there is need for 2,3,5 or 6 colours or may be more.

**Comment by kottenator** [comment]
So far you're the first who asks for it ;) 

Currently it's already possible to do with image background. If there will be more people who can't use image (like you) - I'll implement it. 

BTW, #3 from my previous demo just impossible to do dynamically because conical gradient is not implemented in canvas yet.

**Comment by gthapar** [comment]
Okay I understand. Thanks for providing the solution. :)
