### ISSUE TITLE
Circle with multiple colors

### ISSUE THREAD

**Issue by nahankid** [kottenator/jquery-circle-progress#56]
Hi kottenator,

Your library looks solid and light weight. I'm thinking of using it in our project. Does it support stacked progress (not concentric circles like in another example)? For instance, can it show:, 
30% - no college
20% - undergrads
10% - grads
40% - no data

So, this needs 4 different colors and %ages are configurable.

**Comment by kottenator** [comment]
There is no such functionality right now but I will add it (probably on the weekend, maybe sooner)

**Comment by nahankid** [comment]
Thanks a lot

From:  Rostyslav Bryzgunov
Reply-To:  kottenator/jquery-circle-progress
Date:  Tuesday, 13 October 2015 at 10:14 PM
To:  kottenator/jquery-circle-progress
Cc:  Sharad Gupta
Subject:  Re: [jquery-circle-progress] Circle with multiple colors (#56)


There is no such functionality right now but I will add it (probably on the weekend, maybe sooner)

**Comment by kottenator** [comment]
Hi!

I was thinking on your request recently. There are many possible things to do with "sectors":
- should it be only a "plain color" fill or gradient too? 
- should it be a "static background" or should it be a part of animation?
- maybe I should make default functionality as two sectors: filled and transparent?
- maybe sectors are "too custom" to be a part of the core? (I'm thinking on plug-ins system)

Sorry, I'm still not sure if this functionality should be included into the core. 

But here is a [snippet that does what you need](http://jsbin.com/cabodi/4/edit?js,output).

**Comment by kottenator** [comment]
I decided to not include this functionality into core but to implement it as a plug-in in future. 

Meanwhile you may use my code snippet from above. If there are problems with it - please, put your comments here.

**Comment by Cellofun** [comment]
> I was thinking on your request recently. There are many possible things to do with sectors:
> 
> * should it be only a "plain color" fill or gradient/image too?
> * should it be a "static background" or a part of animation? (dynamic "extension" of all the sectors)
> * maybe I should make the default functionality as two sectors: one - filled, second - transparent?
> * maybe sectors are "too custom" to be a part of the core? (I'm thinking on plug-ins system)
> 
> Sorry, I'm still not sure if this functionality should be included into the core.
> 
> But here is a [snippet that does what you need](http://jsbin.com/cabodi/6/edit?js,output).

Is this functionality still present? The circle in aforementioned snippet doesn't show at all.

**Comment by creativemind1** [comment]
For me as well. the link doesn't show the outpuit
