### ISSUE TITLE
Custom element as cap

### ISSUE THREAD

**Issue by keithpickering** [kottenator/jquery-circle-progress#57]
I need the "cap" of the progress bar to be a textual representation of the value. Basically, on every `circle-animation-progress` event, I need to get the cap position, move the number to that position, and update the value. Is this possible currently?

**Comment by kottenator** [comment]
Please, take a look at #52, that's probably what you're looking for

**Comment by keithpickering** [comment]
Man, this looks perfect. Thanks so much.

**Comment by kottenator** [comment]
You're welcome! ;)
