### ISSUE TITLE
Update color while animating

### ISSUE THREAD

**Issue by keithpickering** [kottenator/jquery-circle-progress#58]
Hi, this plugin is helping me out so much. There's one other thing I'm wondering about:

Is it possible to animate between colors? For instance, if one meter only has 20%, that's a "bad" score and the color of the bar should be red. 50% would be yellow, and 100% would be green. I can think of how to do this by getting the value and updating the color *after* every animation, but is there any way to smoothly fade the color while the animation is happening, so the end color could potentially be any shade between red, yellow, and green? I hope this makes sense.

Alternatively, is it possible to specify a gradient *for the whole bar*, even if it doesn't fill up all the way? For instance, if I set the gradient to go from red to green, currently it ends on green no matter what the final value is. Can I set it to end on green only if the bar is nearly filled?

Thanks again.

EDIT: Found this one: https://github.com/kottenator/jquery-circle-progress/issues/41

This works great, except the middle value between the start and end colors I've chosen is a little "muddy". Is there any way to define a middle step color?

**Comment by kottenator** [comment]
The answers are "yes" and "yes", both possible.

For the first one, you should dynamically calculate fill color for the current value. [Demo No.1](http://jsbin.com/guteko/4)

For the second option you can use image background (because `<canvas>` doesn't have conical asymmetric gradient). [Demo No.2](http://jsbin.com/fekayi/2)

**Comment by kottenator** [comment]
If you want to change the "middle point" color, you'll need to:
```js
if (v < 0.5) {
    // calculate color between "start" and "middle" points
} else {
    // calculate color between "middle" and "end" points
}
```

Yes, #41 is related to the same problem, but in my _Demo No.1 (see above)_ I use `HSL` instead of `RGB` - it's more convenient for color calculation.

**Comment by kottenator** [comment]
Have you solved your problem? May I close this issue?

**Comment by keithpickering** [comment]
Thanks so much for all your help. HSL ended up being a better choice. Now [these](http://i.imgur.com/5Qc2zWV.png) are working perfectly!

**Comment by kottenator** [comment]
YW ;)

**Comment by OptimusPrimo11** [comment]
Do you have any other way for me to access this?

**Comment by kottenator** [comment]
@OptimusPrimo11 - do you mean that the both Demos No.1 and No.2 didn't work for you?

What's your example? Could you create a demo on JSBin / JSFiddle / CodePen?

**Comment by Designburo** [comment]
Well.. the Demos just do not load for me. They Time-Out ? Am currently looking for this solution as well.

**Comment by kottenator** [comment]
Something is wrong with JSBin demos recently... Try to press "Edit" and see the code.

**Comment by Designburo** [comment]
Well I meant to say.. I don't get any page.. the whole page times-out :)

**Comment by kottenator** [comment]
Just add `/edit` at the end of the URL path.

**Comment by Designburo** [comment]
ahhh that worked! Cheers!
