### ISSUE TITLE
circleProgress is not a fuction

### ISSUE THREAD

**Issue by nikogamulin** [kottenator/jquery-circle-progress#59]
HiI tried to copy the main example an am getting the following error:

Uncaught TypeError: $(...).circleProgress is not a function

Does anyone know what might be wrong?

**Comment by nikogamulin** [comment]
Solved.

Loading jQuery script after circle-progress caused the error.

**Comment by devope** [comment]
Hi!

I get the same error
Using webpack

my script.js
```
require('jquery-circle-progress/dist/circle-progress');

$("#dial-1").circleProgress({
    value: 23,
    size: 60,
    lineCap: 'round',
    fill: {
      gradient: ["#005bff", "#005bff"]
    },
    thickness: 33
});

```
