### ISSUE TITLE
Any plan for an indeterminate state ?

### ISSUE THREAD

**Issue by romainbessugesmeusy** [kottenator/jquery-circle-progress#60]
Hey, nice work you've done here. By any chance, do you think about creating an indeterminate state ?

**Comment by kottenator** [comment]
Hi! Sorry for delayed answer. Interesting idea, but not absolutely clear what should be the animation in this case... there are lot of possibilities, someone may want one, someone - another. Let me think about it

**Comment by kottenator** [comment]
I'm going to close this ticket because I don't think that indeterminate state belongs to the _library core_. However, I'll work on #111 to provide convenient way of extending the library with plugins.
