### ISSUE TITLE
Support AMD loaders like requirejs

### ISSUE THREAD

**Issue by jithujose** [kottenator/jquery-circle-progress#61]
Hi, can you add AMD support to this plugin? Thank you

**Comment by kottenator** [comment]
Good idea, I'll implement it in the next version

**Comment by kottenator** [comment]
Wait, don't close it - I'll do that when it's implemented ;)

**Comment by andreiglingeanu** [comment]
@kottenator what's the progress on this? I'd be happy to be able to use this library with webpack.

**Comment by kottenator** [comment]
That's an excellent question! :) I've played with AMD/CommonJS/UMD/SystemJS and I'm going to use UMD approach. Though, to make it CommnonJS-compatible (so you can use it in Webpack/Browserify) - I need to handle dependencies correctly (via NPM's `package.json`) and to release the package to NPM registry. And also to provide _pure browser_ way to use it.

So it's a bunch of work but I'm pretty optimistic about it.

**Comment by andreiglingeanu** [comment]
@kottenator I don't think there's a big list of libraries you depend on. And yes, NPM registry is a pretty important one, lots of the users would to use it this way. How long do you think this will take?

**Comment by kottenator** [comment]
Estimation: 4-8 hours of work. Unfortunately I have very few time during workdays so probably I'll get to it on the weekend.

**Comment by andreiglingeanu** [comment]
Sounds great!

**Comment by andreiglingeanu** [comment]
@kottenator Nothing new on that one? Do you have any chance to make this a reality?

**Comment by kottenator** [comment]
Yes, I'm working on it.

**Comment by kottenator** [comment]
UMD support is implemented but I have a little problem now - @mitchbox has already published `jquery-circle-progress` package on NPM, 9 months ago.

So I have no rights to register my package there :(

**Comment by kottenator** [comment]
@mitchbox - thank you for transferring the package ownership on NPM ;)

**Comment by andreiglingeanu** [comment]
@kottenator Great news!

**Comment by kottenator** [comment]
@andreiglingeanu: yes, I think I've fixed that error. Give it a try and let me know ;)

**Comment by kottenator** [comment]
Finally, new version `jquery-circle-progress@1.2.0` released with UMD support and other recent features. I'm closing this ticket.

**Comment by andreiglingeanu** [comment]
Everything okay. Thank you!
