### ISSUE TITLE
Multiple "circle-animation-end" events firing

### ISSUE THREAD

**Issue by keithpickering** [kottenator/jquery-circle-progress#63]
I'm updating a circle progress meter with a range input like so:

	$('#your-contrib, #employer-contrib').on('updateContrib', function() {
		if ( $this.is('#wellness-score') ) {
			var age = global_age,
			      enroll_age = global_enroll_age,
			      assets = global_assets,
			      salary = global_salary,
			      interest = global_interest,
			      inflation = global_inflation,
			      ret_age = parseInt($('#retire-age-btn').data('value')),
			      your_contrib = parseInt($('#your-contrib').val()) / 100,
			      employ_contrib = parseInt($('#employer-contrib').val()) / 100,
			      ret_type = parseFloat($('#retire-type-btn').data('value'));

			var score = calculateWellnessScore(age,ret_age,enroll_age,assets,interest,salary,your_contrib,employ_contrib,inflation,ret_type);

			if (score > 1) score = 1;
			if (score < 0) score = 0;

			circle.circleProgress('value', score);
		}
	});

And when this animation is complete, I update a line graph elsewhere in the code:

	$('#wellness-score').on('circle-animation-end', function() {
		var circle = $('#wellness-score'),
			instance = circle.data('circle-progress'),
			color = instance.arcFill,
			oldValues = values;

		////////////////////////////////////////////
		// A bunch of graph-specific code here... //
		////////////////////////////////////////////

		// Check if values have changed from last "circle-animation-end" event,
		// destroy the chart and redraw if so, otherwise just update color
		if (values[0] !== oldValues[0]) {
			data.datasets[0].data = values;
			data.datasets[0].strokeColor = color;
			data.datasets[0].pointStrokeColor = color;

			myLineChart.destroy();
			myLineChart = new Chart(ctx).LineWithLine(data, options);
		} else {
			myLineChart.datasets[0].strokeColor = color;
			myLineChart.datasets[0].pointStrokeColor = color;

			myLineChart.update();
		}
	});

My problem is that since the "circle-animation-start" event is fired very often (as the range input is dragged), the "circle-animation-end" event seems to fire multiple times as well. How can I make sure this event ONLY fires when the circle progress meter reaches its final position?

Thanks!

**Comment by keithpickering** [comment]
Decided to just watch for the 'updateContrib' event separately and calculate the color twice.

**Comment by kottenator** [comment]
I think something like [Undescore.js#debounce](http://underscorejs.org/#debounce) is what you need
