### ISSUE TITLE
arcFill color disappears after a certain amount of time

### ISSUE THREAD

**Issue by keithpickering** [kottenator/jquery-circle-progress#64]
See this example: http://dev.keithpickering.net/kmg/retirement/

Everything works so great, but for some reason, the progress bar colors will reset to black (or become otherwise incorrect) if the page is allowed to sit overnight. Do you have any idea what might cause this?

**Comment by kottenator** [comment]
I have an idea how this could happen: you calculate color dynamically, so the function that does the calculation, after "sat overnight", calculates it wrongly (it probably returns `NaN` which resets color to black, the default one)

**Comment by kottenator** [comment]
Have you solved this problem? I'm going to close this ticket.

**Comment by kottenator** [comment]
I'm closing this ticket (I assume that you've handled this problem already). 

And as it seems the problem not in the library code.
