### ISSUE TITLE
how can use it for fullpage.js？

### ISSUE THREAD

**Issue by Gen9YS** [kottenator/jquery-circle-progress#67]
I don't konw how let animate when .active。do you understand ？

**Comment by kottenator** [comment]
Probably [this can help you](#8).

**Comment by kottenator** [comment]
Please, let me know if still have the question/problem.

**Comment by Gen9YS** [comment]
I don't konw why not work.I can’t JS.thank you.

**Comment by kottenator** [comment]
Please, provide full example of what exactly doesn't work

**Comment by kottenator** [comment]
I don't understand the problem and you don't explain it to me so I'm closing this ticket.
