### ISSUE TITLE
stepValue takes child elements value 

### ISSUE THREAD

**Issue by nomoreboredom** [kottenator/jquery-circle-progress#68]
Hi, 

First of all thanks for great tool. 

In my case, I am using stacked circles; as the following (somehow the HTML code does not display). It uses such a parent div (1st circle) and inner child div with less width (2nd circle):

However, if I use the following snippet to initiate:

```js
$('#circle1').circleProgress({
    value: 0.75,
    emptyFill: 'rgba(200, 200, 200, 0.5)'
}).on('circle-animation-progress', function(e, animationProgress, stepValue) {
    $(this).find('.circle1').text(stepValue.toFixed(2)); 
});
 	
$('#circle2').circleProgress({
	value: 0.15,   
	emptyFill: 'rgba(200, 200, 200, 1)' 
}).on('circle-animation-progress', function(e, animationProgress, stepValue) { 
	$(this).find('.circle2').text(stepValue.toFixed(2)); 
});
```

It takes the `stepValue` of the second circle, `0.15` in this case, and appends to relevant divs for both circles. Any idea what may be causing this?

Thanks a lot for this plugin!

**Comment by kottenator** [comment]
Hi!

You're right, the problem exists: the "deepest" nested circle overrides all its parent circles. Actually here is what's going on:

1. parent circle's event is triggered, parent value updated to `0.75`
2. child circle's event is triggered, child value updated to `0.15`
3. child's event is being bubbled up to parent
4. parent circle "catches" the bubbling event and handles it as well, parent value updated to `0.15`

To prevent this, do:

```js
$('#circle1').circleProgress({
    value: 0.75,
    emptyFill: 'rgba(200, 200, 200, 0.5)'
}).on('circle-animation-progress', function(e, animationProgress, stepValue) {
    $(this).find('.circle1').text(stepValue.toFixed(2)); 
});

$('#circle2').circleProgress({
    value: 0.15,   
    emptyFill: 'rgba(200, 200, 200, 1)' 
}).on('circle-animation-progress', function(e, animationProgress, stepValue) { 
    e.stopPropagation(); // <- this line will preven child event bubbling
    $(this).find('.circle2').text(stepValue.toFixed(2)); 
});
```

**Comment by nomoreboredom** [comment]
Hi again, 
Thanks for the explanation and guidance, this did the trick!
