### ISSUE TITLE
Angle gradient

### ISSUE THREAD

**Issue by NeilJS** [kottenator/jquery-circle-progress#73]
Potential enhancement?

Just wondering if canvas can support an angle gradient, so that the finishing color is different to the start color. Linear gradient, even when angled is limited in this respect.

Ideally, an angle gradient with a sharp transition would be best, such as this example: http://stackoverflow.com/questions/18610022/photoshop-like-angle-gradient-in-css3

Alternatively, a conical gradient would be ok but not quite as good as there is no sharp transition for the start/end colors; eg: http://www.nixtu.info/2010/08/html5-canvas-gradients-angular-gradient.html

**Comment by kottenator** [comment]
Hi!

Well, there is problem. 

CSS is not applicable to `<canvas>` and there's no native support for conical gradients yet.

There are different ways show to _emulate conical gradient_ (by drawing lines or points). But IMO they're not good enough (maybe I'm wrong).

So I suggest to use _image fill_ for conical gradients.

**Comment by kottenator** [comment]
I'm closing this ticket for now. Let's return to this question when conical gradients will be implemented in `<canvas>`.

Meanwhile, you can create a snippet (or some kind of plug-in) for `$.circleProgress` that provides this functionality.

**Comment by kottenator** [comment]
Just few links about conical gradients:

* [CSS4 specification](https://www.w3.org/TR/css4-images/#conic-gradients)
* [JS polyfill](http://leaverou.github.io/conic-gradient/) _(a heavy page, be patient)_
