### ISSUE TITLE
Add MinifyJS file

### ISSUE THREAD

**Issue by roshan-lrn** [kottenator/jquery-circle-progress#74]

**Comment by kottenator** [comment]
That's a good idea, I will add it. Meanwhile, you can use the minified version from CDN:
https://cdnjs.com/libraries/jquery-circle-progress

**Comment by roshan-lrn** [comment]
:+1: Thanks. I am installing through bower. :)

**Comment by kottenator** [comment]
Solution implemented in `master`.
