### ISSUE TITLE
How to start at very top of the circle

### ISSUE THREAD

**Issue by ianhd** [kottenator/jquery-circle-progress#75]
What value do I need to use for the progress to start at the very top of the circle, vs. the left? I tried `startAngle: -90` but that made it slightly top left ish. It says the default is `-Math.Pi`. Why not just make it simple angles, like `0` for very top, `90` for the right, `180` for bottom, etc. Thanks!

**Comment by kottenator** [comment]
Try `startAngle: -Math.PI / 2`.

> Why not just make it simple angles?

They are simple angles, but in radians, not degrees.

**Comment by ianhd** [comment]
It would be great if it was determined by degrees, not angles. Friendly
suggestion. Thanks!

On Thu, Feb 4, 2016, 5:04 PM Rostyslav Bryzgunov <notifications@github.com>
wrote:

> Try startAngle: -Math.PI / 2.
>
> Why not just make it simple angles?
>
> They are simple angles, but in radians, not degrees.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kottenator/jquery-circle-progress/issues/75#issuecomment-180072048>
> .
>
-- 
Ian Davis

**Comment by kottenator** [comment]
Unfortunately it can be either radians or degrees, I can't implement both. 
And radians are used for angles in most programming languages so I'd keep them.

**Comment by ianhd** [comment]
How about having an option called `startDegrees: 0` ? Just a thought.

On Thu, Feb 4, 2016 at 5:17 PM Rostyslav Bryzgunov <notifications@github.com>
wrote:

> Unfortunately it can be either radians or degrees, I can't implement both.
> And radians are used for angles in most programming languages so I'd keep
> them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kottenator/jquery-circle-progress/issues/75#issuecomment-180076080>
> .
>
-- 
Ian Davis

**Comment by kottenator** [comment]
I'll think about it, but IMO it's better to have _the only way_ to specify angles (less mistakes, less ambiguity)

**Comment by wasek23** [comment]
You can calculate the angle with this. Just enter the degree in this formula.

Math.PI * ((degree / 360) * 2 - 0.5)

0 ° will start from the top.
