### ISSUE TITLE
On hover is not working

### ISSUE THREAD

**Issue by iamsuz** [kottenator/jquery-circle-progress#78]
I create multiple circles dynamically. i wrote single script for circle and using foreach in php laravel i create multiple. and i used hover to animate it. Its working only for first and all others are animated at once when hover first circle and rest are not functional on hover.

**Comment by kottenator** [comment]
Please, provide an HTML/JS code example so I could help you.

**Comment by kottenator** [comment]
Here is a [working demo for you](http://jsbin.com/qosocu/2/edit?html,css,js,output). Animation starts on hover, separate for each circle.

I'm closing this issue. If you think the problem still exists - please, reopen it.
