### ISSUE TITLE
Any option to control the animation delay?

### ISSUE THREAD

**Issue by ciprianflorescu** [kottenator/jquery-circle-progress#79]
I want to make the animations start a bit later after they got in viewport. Any option to set a delay for each animation?

**Comment by kottenator** [comment]
This was discussed in #8 issue.

Here is a snippet for you if you also want to add a delay:

```js
var el = $('#circle'),
    _timeout,
    _delay = 500;

el.appear({ force_process: true });

el.on('appear', function() {
  _timeout = setTimeout(function() {
    el.circleProgress({ value: 0.7 });
  }, _delay);
});

el.on('disappear', function() {
  clearTimeout(_timeout);
});
```

**Comment by kottenator** [comment]
I believe my snippet solves the problem. I'm closing this ticket. Feel free to reopen it
