### ISSUE TITLE
lazyload or waypoint kind of waiting time

### ISSUE THREAD

**Issue by nmvivek** [kottenator/jquery-circle-progress#8]
how can i animate circle while scrolling down to page ? my page is quite long and this plugin come just above the footer, but it animate, when page loads and when scroll down, can not see the circle progress effect ?

**Comment by Khabir-Ahamed** [comment]
This is an awesome plugin and i used it before.Now i want to know have any option of this circular progress bar for starting progress when visible it after scrolling???? 

please inform me i need it urgently!

**Comment by kottenator** [comment]
@Khabir-Ahamed: sorry but I don't understand - doesn't the example work for you?

**Comment by Khabir-Ahamed** [comment]
i want to animate my progress bar only when i view it!...and how can i do this????

**Comment by kottenator** [comment]
Did you try to use my example above (with `jquery.appear`) ?????!!!

**Comment by Khabir-Ahamed** [comment]
no brother i do not use it!

**Comment by kottenator** [comment]
That's exactly what you need:
- you don't start the circle animation until it appears in the viewport

**Comment by Khabir-Ahamed** [comment]
ok,brother i will try as your suggested example.If i face any problem then
i will knock you!

2015-10-14 22:16 GMT+06:00 Rostyslav Bryzgunov <notifications@github.com>:

**Comment by Chirpizard** [comment]
Hi, @kottenator 
First, I love this script! So beautiful. I'm trying to use the solution you shared above with jquery.appear, but I'm unable to get it to work. I of course installed jquery.appear, and changed your example to work with my circle ID, but it's not working. Where do I use that script exactly? Sorry for this type of question, I'm still learning JS and jQuery.

Thanks!

**Comment by longhoang2984** [comment]
Hello! I want to show <span></span> near the end progress value how can I do!
Many thanks!

**Comment by coreatgit** [comment]
@kottenator 
can we trigger the animation on a button click also  updating the startAngle of the animation before it begins..??

**Comment by kottenator** [comment]
@longhoang2984 - see the #52 ticket

**Comment by kottenator** [comment]
@coreatgit - yes, we can do that.

To trigger animation on a button click:

```js
var el = $('#circle-container'),
    btn = $('#trigger-button'),
    val = 0.7;  // get it from somewhere, somehow

// Option 1: pre-render an empty circle
circle.circleProgress({ value: 0 });
btn.click(function() {
  circle.circleProgress({ value: val });
});

// Option 2: render on click
btn.click(function() {
  circle.circleProgress({ value: val });
});
```

**Comment by kottenator** [comment]
@longhoang2984, @coreatgit - sorry for delayed answer. I've lost your comments because you had posted them in a closed ticket. 

If you want to get the answer faster next time - please, reopen a ticket or create a new one ;)

**Comment by mrshoaib** [comment]
Hi kottenotor i cant understand how can i used it please help me.................

**Comment by YueminHu** [comment]
Great plug-in, awesome!!Just a complimentary comment!

**Comment by kottenator** [comment]
@YueminHu - thanks! ;)

**Comment by oldejuk** [comment]
var el = $('.circle'),
    inited = false;

el.appear({ force_process: true });

el.on('appear', function() {
  if (!inited) {
    el.circleProgress({ value: 0.7 });
    inited = true;
  }
});

how can i do this in Jquery? help plz)

**Comment by kottenator** [comment]
Hi!

All you need to do is:

   - include jquery.js into your HTML
   - then include jquery.appear.js (download from here
   <https://github.com/morr/jquery.appear>)
   - then run the code snippet from my comment
   <https://github.com/kottenator/jquery-circle-progress/issues/8#issuecomment-65407422>

It should work.

On Sun, Jun 5, 2016 at 6:08 AM Alex <notifications@github.com> wrote:

> var el = $('.circle'),
> inited = false;
>
> el.appear({ force_process: true });
>
> el.on('appear', function() {
> if (!inited) {
> el.circleProgress({ value: 0.7 });
> inited = true;
> }
> });
>
> how can i do this in Jquery? help plz)
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/kottenator/jquery-circle-progress/issues/8#issuecomment-223803651>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAWr2rKwtsrHQMgHpCw1GGuCJ2_3Zwihks5qIqAbgaJpZM4DDkO5>
> .
>
-- 
--
With regards,
Rostyslav

**Comment by SamThilmany** [comment]
I want this issue to revive because I would like to know how to animate several visible progress bars.

**Comment by happy2deepak** [comment]
@kottenator is there a way to change the Arc color? Suppose I want to give two colors ?

![2color](https://cloud.githubusercontent.com/assets/1978524/17929530/b517e564-6a1e-11e6-8818-2a7d09428181.PNG)
What's the syntax to set two different colors?

**Comment by atiqbd** [comment]
HI, when we have more than one circle progress how we can use this? Changing .circle selector like .circle.second doesn't work. any idea?

var el = $('.circle'),
inited = false;

el.appear({ force_process: true });

el.on('appear', function() {
if (!inited) {
el.circleProgress({ value: 0.7 });
inited = true;
}
});

**Comment by kottenator** [comment]
Instead of `inited` global variable use `$(this).data('inited', true)`.

**Comment by atiqbd** [comment]
sorry, this not works, i'm new onto this, any full code would be much helpful. Thank you.

**Comment by Jiroscopes** [comment]
how to use with multiple on the same page? you cant just change selectors

**Comment by kottenator** [comment]
@atiqbd  - try this:

```html
<div class="circle one"></div>
<div class="circle two"></div>
<div class="circle three"></div>
```

```css
.circle {
  margin-bottom: 1000px;
}
```

```js
var circles = $('.circle');

circles.appear({ force_process: true });

circles.on('appear', function() {
  var circle = $(this);
  if (!circle.data('inited')) {
    circle.circleProgress({ value: 0.7 });
    circle.data('inited', true);
  }
});
```

**Comment by amichel86** [comment]
Thanks @kottenator for this awesome plugin and the solution, you're a god! 🗡

**Comment by kottenator** [comment]
Thank you, @amichel86! 

I really appreciate when people like my creation and when they're saying good words to me :) That's the best and the only reward I get for my effort here.

**Comment by amichel86** [comment]
@kottenator I don't mind paying you a beer, what's your PayPal? haha

**Comment by kottenator** [comment]
Don't think I told that to get a beer :) I really appreciate your words, that's all.

_(but my e-mail is in the source code, it's for PayPal too)_.

**Comment by joeyre** [comment]
Great plugin and solution, loving it so far! Is there an easy solution to having multiple circles on one page each with different values that animate when you scroll them?

**Comment by Jiroscopes** [comment]
@joeyre you can just make a div for each one and call it a different name. This is what I did.
```
        $('.progress-bar').gradientProgressBar({
          value: 0.95
        });
        //end progress-bar 1
        $('.progress-bar-2').gradientProgressBar({
          value: 0.90
        });
        //end progress-bar-2
```

**Comment by joeyre** [comment]
@Jiroscopes ahh perfect thank you!

**Comment by nataliakielbicka** [comment]
Is it possible to use appear.js with circleProgress plugin without setting any value?
We have:
`el.circleProgress({ value: 0.7 });`
but I want to use it in wordPress and my html is:
```
<div class="circle" data-value="0.94">
                        <span>94%</span>
                    </div>
```

**Comment by kottenator** [comment]
@nataliakielbicka - this issue seems to be the most popular in my project :)

See [this demo](http://jsbin.com/qupohek/3/edit?js,output) - it uses `Waypoints` but you can easily convert it to `jquery.appear`.

The idea is:

* render circle(s) with `0` value at page load;
* then _on appearance_ - set the correct circle value.

This can be done in various ways.

**Comment by amichel86** [comment]
@nataliakielbicka here's a complete example that I use on one of my recent project:

`	// Progress Circle
  $('.circle__progress').circleProgress({
    value: 0,
    size: 140,
		startAngle: 4.7,
		emptyFill: "#202020",
    fill: {
      gradient: ["#fe6b26", "#cd571e"]
    }
  });	
	
	var circles = $('.circle__progress');

	circles.appear({ force_process: true });

	circles.on('appear', function() {
		var circle = $(this);
		if (!circle.data('inited')) {
			circle.circleProgress({ 
				value: $(this).data('value'),
			});
			circle.data('inited', true);
		}
	});	`

**Comment by Khabir-Ahamed** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/a74b26e646",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Khabir is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.
