### ISSUE TITLE
colour fill from CSS colour value

### ISSUE THREAD

**Issue by lougreenwood** [kottenator/jquery-circle-progress#80]
Hi,

I'm currently using circle-progress many places in my project, as such, I'm making doing my initialisation in html data-attributes and 1 generic javascript method to draw all progress circles.

All contextual data to draw the circle is passed over to the js via data-attributes - data such as the value, fill colour etc.

My problem is that I want to set the fill colour of the progress circle based upon the value of a css class that defines progress (think bootstrap's progress-success, progress-danger etc). However, because circle progress uses the canvas, I don't think I have access to css styling of fill colour via css. All of my CSS classes are written in Sass.

I know I can go down the hacky route of setting the css class (which contains a fill colour value) on the circle progress container, grab that class over css and substitute it in via my generic circle progress js init code, but as mentioned earlier, I'm trying to pass all data over data-attributes and keep the init js code as generic as possible to cover all of my use cases.

So my question is, is there any way that I dynamically set the fill colour using only dynamically generated html (server side PHP), data-attributes and CSS styling?

Here's my example code: https://jsfiddle.net/rbyftf4k/1/

Thanks!

**Comment by lougreenwood** [comment]
Works perfectly, thank you :+1:

**Comment by lougreenwood** [comment]
Sorry, to re-open, but I've hit an issue when I dynamically change the colour (via a class).

To add some context, I'm using jquery to dynamically add a class to the circle as a user completes certain actions, this class sets a different colour depending on the percent value, something like this - https://jsfiddle.net/qvct6f0o/

However, I can't get the circle to update it's fill colour without using "$('#circle').circleProgress({ value: 0.5, fill: { color: 'orange' }});"

Any ideas?

Thanks

**Comment by kottenator** [comment]
You mean that you want to automatically "catch" the moment when CSS class name changes and to re-trigger the circle animation? That's pretty hard - http://stackoverflow.com/questions/1950038/jquery-fire-event-if-css-class-changed

I suggest to re-trigger `.circleProgress({ value: new val })` _manually_ when you update the CSS class name (and you can still use my snippet from above so the circle will get the color from current CSS class)

**Comment by lougreenwood** [comment]
Thanks of your reply,

I've go too need to catch any jquery events, so your suggestion should be fine, however when I try your suggestion (I'm actually doing '$(this).circleProgress("value", percentageCompleted);' ) after the CSS class is added, whilst the value updates, the colour does not (although I can the class is added n the inspector) - I've tried adding an important to the CSS class to override, but still no luck.

Additionally, I've tried to throw in a .circleProgress('redraw'); after re-setting the value, but again, no luck....

**Comment by kottenator** [comment]
OK, I'll take a closer look

**Comment by kottenator** [comment]
My snippet above was a bit complicated. [I've updated it](http://jsbin.com/rotove/4/edit?html,css,js,output) and it does what you want now.

**Comment by kottenator** [comment]
And again I hope that I've solved your problem this time so I'm closing the ticket. Feel free to reopen ;)

**Comment by happy2deepak** [comment]
@kottenator is there a way to change the Arc color? Suppose I want to give two colors ?

![2color](https://cloud.githubusercontent.com/assets/1978524/17929530/b517e564-6a1e-11e6-8818-2a7d09428181.PNG)
What's the syntax to set two different colors?

**Comment by happy2deepak** [comment]
@kottenator thanks found it:
`emptyFill: "rgba(0, 0, 0, 0)"`
