### ISSUE TITLE
Overshoot

### ISSUE THREAD

**Issue by BillyBlaze** [kottenator/jquery-circle-progress#84]
Do you think it's possible to support overshoot?

In my case, I am visualizing the actual temperature against the target temperature and once the target has been reached, the heat turns down, after reaching the target it can still get a few degrees hotter hence the overshoot. Another way I need overshoot is if they change the target to a lower number, then I could also visualize the temperature dropping.

Also in addition, is it perhaps an idea to add the plugins inside the dist folder?

**Comment by kottenator** [comment]
I don't quite understand - what is overshot? Could you give some example(s)?

**Comment by BillyBlaze** [comment]
Paint skills FTW! :+1: 

With the following example: Light green is the default fill color, and dark green is the overshoot fill color, the following circle repesents a filled circle of +/-130% (or a value of 1.3)

![image](https://cloud.githubusercontent.com/assets/445608/14179022/a45fc054-f75d-11e5-865d-85bd895bc5e9.png)

Some math:
Target temp: 180 degrees
Actual temp: 200 degrees
Circle value: 1.11111

I hope this makes more sense to you.

**Comment by kottenator** [comment]
Yes, that makes sense, thanks! :)

It looks for me like not a core functionality but rather a plugin/snippet with this custom behavior.

[Here is a snippet for you](http://jsbin.com/cewoli/2/edit?html,css,js,output).

**Comment by kottenator** [comment]
I hope my snippet helped you. I'm closing the ticket. Feel free to reopen it if there is still something to do.

**Comment by BillyBlaze** [comment]
Sorry, thanks for the snippet! :+1:
