### ISSUE TITLE
Duration not working

### ISSUE THREAD

**Issue by mapodev** [kottenator/jquery-circle-progress#85]
Hello,

I have this set up:

    jQuery(function($) {
                $("#circleCounter").circleProgress({
                    duration: 5000,
                    value: 1,
                    animationStartValue: 0.0,
                    fill: { color: 'orange' }
                });

            });`

On this example, the duration is not used. It animates immediately into value.

**Comment by mapodev** [comment]
Ok, I didn't see that animation is a own object. 

With
```

animation: {
                            duration: 10000,
                            easing: 'circleProgressEasing'
                        },
```

it is working

**Comment by kottenator** [comment]
I'm glad that you've solved your problem by yourself ;)
