### ISSUE TITLE
How can i redraw startAngle ?

### ISSUE THREAD

**Issue by Malin88** [kottenator/jquery-circle-progress#86]
Hi?
I can nicely redraw value with animation by using this code:
`$('.circle').circleProgress('value', 0.5);`
but how can I redraw with animation the second end of bar ?
this code don't work :/
`$('.circle').circleProgress('startAngle', 5);`

**Comment by kottenator** [comment]
Yes, currently only `value` has its own "update" method. But you can achieve what you want - [here I've created a snippet for you](http://jsbin.com/cewoli/3/edit?html,css,js,output).

**Comment by Malin88** [comment]
Thanks, you're great, this solves my problem :)
