### ISSUE TITLE
Needed - emptyFill

### ISSUE THREAD

**Issue by m-kermani** [kottenator/jquery-circle-progress#87]
Now **emptyFill** is not working and just has its own default value

**Comment by kottenator** [comment]
I'm sorry but I haven't changed anything for 8 months. 
Please, provide details of your problem: code example, working demo, etc.

**Comment by m-kermani** [comment]
Sure; Sorry I did not know that

in the documentation, about the **emptyFill** you wrote:

> Color of the "empty" arc. Only a color fill supported by now 
> Default: "rgba(0, 0, 0, .1)"

_Only a color fill supported by now_; and does this mean I can't change it?!

**Comment by kottenator** [comment]
Well, of course no. You can set any color there:
```js
$('.circle').circleProgress({
  emptyFill: '#336699'
});
```

**Comment by m-kermani** [comment]
Oh; Now I get it!

But I was thinking that mean I can't set, and I tried {} and did not work

Sorry, and thanks again

**Comment by kottenator** [comment]
You're welcome ;)
