### ISSUE TITLE
Value Progress displayed as Percentage

### ISSUE THREAD

**Issue by prokes** [kottenator/jquery-circle-progress#89]
Hello -

Great product, thank you for making this.

I would like to display my Value as a percentage instead of as a decimal. Looking at these [examples](http://kottenator.github.io/jquery-circle-progress/), I want the 3rd blue one to display as "75%" instead of ".75". 

I have modified per below and it mostly works but as it counts up to my Value (ex: 61) some Values display very long (ling 31.0000000000002) which makes it look choppy. I would expect each to be rounded consistently. The result (61%) is correct but it displays some very long (decimal) numbers along the way.

My jquery is not very strong, is there a better way to do this?

Thanks,

Evan

```js
$('.circle').circleProgress({
  value: "{{ percentage_complete }}",
  fill: {
    gradient: ["#388126", "#41952d", "#52bc37"]
  }
}).on('circle-animation-progress', function(event, progress, stepValue) {
  $(this).find('strong').text(String(((stepValue.toFixed(2)).substr(1))*100)+ '%');
});
```

**Comment by kottenator** [comment]
Here I've modified your code:


```js
$('.circle').circleProgress({
  value: "{{ percentage_complete }}",
  fill: {
    gradient: ["#388126", "#41952d", "#52bc37"]
  }
}).on('circle-animation-progress', function(event, p, v) {
  $(this).find('strong').text(Math.round(v * 100) + '%');
});
```

**Comment by prokes** [comment]
Wow thanks @kottenator! I really appreciate your help, as it works beautifully now.

It seems this would be a common use case so hopefully someone else can use this in the future. I made a slight modification and on the last line replaced 'v' with 'stepValue'.

```js
$('.circle').circleProgress({
    value: "{{ percentage_complete }}",
    fill: {
		gradient: ["#388126", "#41952d", "#52bc37"]
			}
}).on('circle-animation-progress', function(event, progress, stepValue) {
	$(this).find('strong').text(Math.round(stepValue * 100) + '%');
	});
```

**Comment by kottenator** [comment]
:+1:
