### ISSUE TITLE
Cannot Change Fill Color

### ISSUE THREAD

**Issue by camscottFS** [kottenator/jquery-circle-progress#90]
![progressbarcolorfail](https://cloud.githubusercontent.com/assets/7515080/14907737/731f028e-0d92-11e6-8688-0e0f070e0e8c.png)
The fill color will not change at all no matter what I do. the emptyFill changes though.

I'm using your 1.1.3 and didn't edit anything but the fill.

```js
/**
 * Fill of the arc. You may set it to:
 *   - solid color:
 *     - { color: '#3aeabb' }
 *     - { color: 'rgba(255, 255, 255, .3)' }
 *   - linear gradient (left to right):
 *     - { gradient: ['#3aeabb', '#fdd250'], gradientAngle: Math.PI / 4 }
 *     - { gradient: ['red', 'green', 'blue'], gradientDirection: [x0, y0, x1, y1] }
 *   - image:
 *     - { image: 'http://i.imgur.com/pT0i89v.png' }
 *     - { image: imageObject }
 *     - { color: 'lime', image: 'http://i.imgur.com/pT0i89v.png' } - color displayed until the image is loaded
 */
fill: { color: '#3aeabb' },

/**
 * Color of the "empty" arc. Only a color fill supported by now
 * @type {string}
 */
emptyFill: '#000',
```

Empty fill works, the regular fill won't do anything. I need to use a white background where the progress circle is located and this is really irritating. The default color is white and it won't change at all.

My current div class is "progressbar"

**Comment by kottenator** [comment]
Please, provide your code example, live demo or something like that, so I can see the problem

**Comment by camscottFS** [comment]
`         <div class="col-md-8 circle-skills nopadding height-400" style="background: #fff;">
            <div class="padding-50 wow fadeInLeft" data-wow-delay="0.6s" data-wow-offset="5">
               <h3 class="font-accident-two-normal uppercase fontcolor-invert">Development Progress</h3>
               <div class="row">
                  <div class="col-sm-4 nopadding">
                     <div class="progressbar" data-animate="false">
                        <div class="circle font-accident-one-normal fontcolor-invert" data-percent="83">
                           <div></div>
                           <h4 class="font-accident-one-normal uppercase circle-one">Overall</h4>
                           <p class="small">
                              
                           </p>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-4 nopadding">
                     <div class="progressbar" data-animate="false">
                        <div class="circle font-accident-one-normal fontcolor-invert" data-percent="77">
                           <div></div>
                           <h4 class="font-accident-one-normal uppercase circle-two">Raids</h4>
                           <p class="small">
                              
                           </p>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-4 nopadding">
                     <div class="progressbar" data-animate="false">
                        <div class="circle font-accident-one-normal fontcolor-invert" data-percent="75">
                           <div></div>
                           <h4 class="font-accident-one-normal uppercase circle-three">Dungeons</h4>
                           <p class="small">
                              
                           </p>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-4 nopadding">
                     <div class="progressbar" data-animate="false">
                        <div class="circle font-accident-one-normal fontcolor-invert" data-percent="86">
                           <div></div>
                           <h4 class="font-accident-one-normal uppercase circle-four">Battlegrounds</h4>
                           <p class="small">
                             
                           </p>
                        </div>
                     </div>
                  </div>
                    <div class="col-sm-4 nopadding">
                     <div class="progressbar" data-animate="false">
                        <div class="circle font-accident-one-normal fontcolor-invert" data-percent="92">
                           <div></div>
                           <h4 class="font-accident-one-normal uppercase circle-five">Spells</h4>
                           <p class="small">
                             
                           </p>
                        </div>
                     </div>
                  </div>
                    <div class="col-sm-4 nopadding">
                     <div class="progressbar" data-animate="false">
                        <div class="circle font-accident-one-normal fontcolor-invert" data-percent="90">
                           <div></div>
                           <h4 class="font-accident-one-normal uppercase circle-six">Talents</h4>
                           <p class="small">
                              
                           </p>
                        </div>
                     </div>
                  </div>
                    <div class="col-sm-4 nopadding">
                     <div class="progressbar" data-animate="false">
                        <div class="circle font-accident-one-normal fontcolor-invert" data-percent="80">
                           <div></div>
                           <h4 class="font-accident-one-normal uppercase circle-seven">Quests</h4>
                           <p class="small">
                             
                           </p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>`

The JS file used is the 1.1.3 from here, with no changes but the fill color.

**Comment by kottenator** [comment]
That's the most interesting - please, show how you initialize circles in JS

**Comment by apatikgg** [comment]
Hello, I looked up the source code of your page http://realtbc.com and I notice custom.js is where you initialize circleProgress. 
You actually are overwritting the color fill option, which you already modified in circle-progress.js.

custom.js (lines 271-299) : 

```
/* Circle Progress */
(function () {
	function animateElements() {
		$('.progressbar').each(function () {
			var elementPos = $(this).offset().top;
			var topOfWindow = $(window).scrollTop();
			var percent = $(this).find('.circle').attr('data-percent');
			var percentage = parseInt(percent, 10) / parseInt(100, 10);
			var animate = $(this).data('animate');
			if (elementPos < topOfWindow + $(window).height() - 30 && !animate) {
				$(this).data('animate', true);
				$(this).find('.circle').circleProgress({
					startAngle: -Math.PI / 2,
					value: percent / 100,
					thickness: 3,
					fill: {
						color: '#ffffff'
					}
				}).on('circle-animation-progress', function (event, progress, stepValue) {
					$(this).find('div').text((stepValue * 100).toFixed(1) + "%");
				}).stop();
			}
		});
	}

	// Show animated elements
	animateElements();
	$(window).scroll(animateElements);
})();
```

You can either change the fill color in this file (line 284) to the color that you wanted, or remove this option so that the color that you already set in circle-progress.js gets applied.

**Comment by kottenator** [comment]
OK, [here is a snippet for you](http://jsbin.com/tuxajep/2/edit?js,output)

**Comment by camscottFS** [comment]
That would explain it. Fixed. Thank you guys!

**Comment by kottenator** [comment]
You're welcome! ;)
