### ISSUE TITLE
stepValue isn't defined and keeps "running"

### ISSUE THREAD

**Issue by gareth-gillman** [kottenator/jquery-circle-progress#93]
Using this handy script on a website, checked the browser error log (firefox & chrome) and see the following:

![stepvalue](https://cloud.githubusercontent.com/assets/3321908/15091645/15f567d6-1447-11e6-9c15-5a86202e4fca.png)

My code is:

```
$('.first.circle').circleProgress({
 value: 0.6,
 emptyFill: "#F4F4F4",
 size: 150,
 fill: { color: "#3BB9BC" }
}).on('circle-animation-progress', function (event, progress) {
 $(this).find('strong').text(String(stepValue.toFixed(2)).substr(1));
});
```

This won't cause an issue for sites using 1 progress circle but if you have a few then having a script constantly "running" (the bottom number keeps increasing), could that effect the speed of the website?

p.s. using jquery 1.11.1 and 1.12.3 (upgraded incase it was an issue with the older version).

Is there a fix for this, I did try setting stepValue as a variable but it removes the %age count.

**Comment by simonmacfadyen** [comment]
You aren't defining the variable `stepValue`. 

stepValue = $(this).data('value');

**Comment by gareth-gillman** [comment]
I used the example #3 from http://kottenator.github.io/jquery-circle-progress/examples.js which doesn't define the stepValue but works fine.... 

Tried your code and doesn't work either,

`$('.first.circle').circleProgress({
  value: 0.6,
  emptyFill: "#F4F4F4",
  size: 250,
  fill: { color: "#3BB9BC" }
 }).on('circle-animation-progress', function (event, progress) {
  var stepValue = $(this).data('value');
  $(this).find('strong').text(String(stepValue.toFixed(2)).substr(1));
 });`

**Comment by simonmacfadyen** [comment]
Perhaps you haven't a data attribute named `data-value` on your `<div>`? If that's the case, & looking at the [API](https://github.com/kottenator/jquery-circle-progress#api), it states you can get the value with:

`var value = $('.circle').circleProgress('value'); // 0.5`

Updating the code above, you'd use the `progress` multiplied by the `value`. 
```
$('.first.circle').circleProgress({
    value: 0.6,
    emptyFill: "#F4F4F4",
    size: 250,
    fill: {
      color: "#3BB9BC"
    }
  }).on('circle-animation-progress', function(event, progress) {
      var value = $('.circle').circleProgress('value') * progress;
      $(this).find('strong').text(value.toFixed(2));
});
```

It really does depend on how your HTML markup. :)

**Comment by kottenator** [comment]
@gareth-gillman: has @simonmacfadyen solved your problem?

**Comment by gareth-gillman** [comment]
Not had chance to test yet, will do tomorrow morning :)

**Comment by kottenator** [comment]
I'm closing this ticket. Feel free to reopen if you still have problems
