### ISSUE TITLE
Stacked bars

### ISSUE THREAD

**Issue by rendermouse** [kottenator/jquery-circle-progress#94]
Please add a way to draw multiple colored bars along the arc, which would allow for situations where multiple values sum to 100%.

**Comment by kottenator** [comment]
I was considering this functionality and decided that it's too complex to be in the "core". But there is a snippet in #56 that might help you.

**Comment by josezulu** [comment]
I love the way the stack bars work in the snippet #56!

This is maybe off topic, but I was always wondering if a "circular" gradient can be implemented. Like the following picture: [click here](http://i537.photobucket.com/albums/ff334/Ramjet64/masked-circular-ramp.jpg)

At the moment, the gradient is a linear gradient masked out by the circle. It's not exactly what I'm looking for, as I would like the gradient to start at transparent and finish at blue over circle line itself.

Maybe with your stacked bars it can be done if the sectors support gradients (sorry I did not try it), or can this be implemented in the "core"?

**Comment by kottenator** [comment]
Yes, I'd like to provide conical gradient fill but it's not supported by `<canvas>` AFAIK. See my comment in #73 (and also a snippet).

**Comment by rendermouse** [comment]
Thank you for the link to the snippet.  I do suppose that I was asking for a circle **graph**, not a true circle progress bar, so it would be outside of core functionality. It turned out that I had even more custom features to implement, so I ended up writing my own canvas code.

**Comment by kottenator** [comment]
Oh, I see. Well, good luck! ;) Then I'm closing this ticket.
