### ISSUE TITLE
Firefox 46.0.1 Draw Bug

### ISSUE THREAD

**Issue by someother1** [kottenator/jquery-circle-progress#95]
We just discovered this bug:

The result from:

```
$(document).ready(function()
{
	$('.circle').circleProgress({
		value: 0,
		size: 150, 
		fill: {gradient: ["#000", "#000"]},
		thickness: 15,
		emptyFill: "#ccc",
		lineCap: 'square',
		startAngle: -1.5,
		animation: {
			duration: 200
		}
	});
});
```

couses in firefox following image:
http://i.imgur.com/7FQF7Pf.png

Fiddle is here:
https://jsfiddle.net/q16ntjt3/

**Comment by kottenator** [comment]
I've checked this case, it's not a bug. You use `lineCap: 'square'` which renders start/end of the line _a bit outside_ of the boundaries.

See the [MDN specification](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap).

**Comment by kottenator** [comment]
I hope I've solved this issue. Feel free to reopen, if not.

**Comment by andreiglingeanu** [comment]
@kottenator I bet that's what makes tests on #83 to fail.
