### ISSUE TITLE
Not redraw but just increase actual value

### ISSUE THREAD

**Issue by dimitrilahaye** [kottenator/jquery-circle-progress#96]
Hello! Is it possible to increase actual value of the circle but to not have the circle redrawed entierly?
For example, if circle value is 0.5 and we set it to 0.7, we can see the filler increase of 0.2 instead actual comportment (the filler go back to 0 and increase to 0.7).

Thanks by advance!

**Comment by kottenator** [comment]
Yes, it's possible. I've implemented [API to update the value](https://github.com/kottenator/jquery-circle-progress#getset-value).

**Comment by dimitrilahaye** [comment]
Yeah I didn't get it! Thanks a lot :)
