### ISSUE TITLE
show text or percentage on process bar edge

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [kottenator/jquery-circle-progress#97]
hi,
thank you for this cool plugin

we have something like this. is there any chance to create something like this?
![Image of progressbar](<https://monosnap.com/file/omonwi0H1UvlOl5XApjnaL16EhvWrr.png)

**Comment by kottenator** [comment]
Please, take a look at #57 and #52

**Comment by kottenator** [comment]
I home those tickets should help you. I'm closing this one.

**Comment by Mohsen-Khakbiz** [comment]
thank you so much. it really helped
