### ISSUE TITLE
numeric value in the middle of circle

### ISSUE THREAD

**Issue by pourush77** [kottenator/jquery-circle-progress#98]
Hi ,
Thanks for the wonderful plugin.my requirement is a numeric value must come in the middle of the circle and that must be dynamic coming from some database. 

can you please tell what to do ?
My code is :

```js
$(document).ready(function() {
  $('#circle').circleProgress({
    value: 0.75,
    size: 80,
    fill: {
      gradient: ["red", "orange"]
    }
  });
});
```

**Comment by pourush77** [comment]
My code is like this : <script>
        $(document).ready(function()
                          {
             $('#circle').circleProgress({
        value: 0.75,
        size: 80,
        fill: {
            gradient: ["red", "orange"]
        }
                 });
                    
            
        });
</script>

**Comment by kottenator** [comment]
The task is very specific for your application and doesn't seem so complex:

```html
```

**Comment by pourush77** [comment]
@kottenator : thanks alot :)

**Comment by kottenator** [comment]
You're welcome! I hope I've solved your issue. I'm closing this ticket.

**Comment by pourush77** [comment]
Hi ,
I tried all working but still not able to see the value
My code :+1:  <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style> 
            body{
                
                padding-top: 150px;
                text-align: center;
                }
            .circle{position: relative;
                display: inline-block;
                
            }
            .circle .value{
                position: absolute;
                z-index: 1;
                left: 0;
                right: 0;
                top: 50%;
                margin-top: -15px;
                height: 30px;
                font: :24px/30px sans-serif;
                text-align: center;
                        
                            }
                    
            
        
        </style>
       
    <title>Circular progressbar</title>
    <script src="js/jquery-2.2.4.min.js"></script>
    <script src="js/circle-progress.js"></script>
         
        <script>
            $(document).ready(function(){
            var circle=$('.circle'),value=circle.children('.value');
                
                circle.circleProgress().on('circle-animation-progress',function(e,p,v){
                    value.text((v*100).toFixed());
                    
                    
                });
                
        
            
          
                
            });
                 
        </script>
        </head>
<body>
    
    <div class="circle" data-value="0.7"></div>
    <div class="value"></div>
    </body>
    </html>

**Comment by pourush77** [comment]
I want to ask something ..Can I put this functionality into a canvas ?If yes then how ?
or say my requirement is I need to make a dashboard with these UI features

Imagine I have a white colour box of height=256px  and width=170px and inside that I have this circular plugin which will fetch the value from DB and show to the user.
How to do that ?

**Comment by pourush77** [comment]
Something like this I want 
![sample1](https://cloud.githubusercontent.com/assets/19535093/15857646/10fda85a-2cda-11e6-89bf-0438bd52bd5e.PNG)

**Comment by pourush77** [comment]
Should I use Canvas ? div ? I am confused ? :(

**Comment by kottenator** [comment]
`div`s are fine for your need. It's not a problem to have multiple circles on a page.

**Comment by pourush77** [comment]
Hi kottenator,
Is it possible that the data-value property of the Div tag can be dynamically changed ?
say I have input type textbox and a button .On click of that button and taking that value the circle should be redrawn?

If so how to do it with jquery?

**Comment by kottenator** [comment]
If you want to change the circle's value - use `el.circleProgress('value', newValue)`

**Comment by pourush77** [comment]
can u please give an example : 
here is my code : 
 <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style> 
            body{
                
                padding-top: 150px;
                text-align: center;
                    background-color: lightgrey;
                }
            
            
            
            .circle{position: relative;
                display: inline-block;
                height: 106px;
                width:106px;
                
            }
            .circle .value{
                position: absolute;
                z-index: 1;
                left: 0;
                right: 0;
                top: 50%;
                margin-top: -15px;
                height: 30px;
                font: :24px/30px sans-serif;
                text-align: center;
                
                        
                            }
                    
            .mydiv{ width: 170px;
                    height:256px;
                    
                
                
                background-color: white;}
            .heading{
                font-family: sans-serif;
                font-size: 12px;
                color: #5C5F6A;
                 padding-top: 15px;
               padding-bottom: 40px;
                
            }
            #div1{
height: 40px;
    width: 170px;
    border-color: lightgrey;
    border-width: thin;
    
                    margin-top: 33px;
                border-top-style: outset;


}
            .subdiv{
                
                width: 54px;
                border-left-style: outset;
              
                border-color: lightgray;
                float: left;
                height: 40px;
                border-width: thin;
                
                
            }

            
            .myimg{
                
                padding-top: 10px;
            }
        
        </style>
       
    <title>Circular progressbar</title>
    <script src="js/jquery-2.2.4.min.js"></script>
    <script src="js/circle-progress.js"></script>
         
        <script>
            $(document).ready(function(){
            var circle=$('.circle'),value=circle.children('.value');
                
                circle.circleProgress({startAngle:-190}).on('circle-animation-progress',function(e,p,v){
                    value.text((v*100).toFixed());
                    
                    
                });
                
        
            
          
                
            });
                 
        </script>
        </head>
<body>
    
    <div class="mydiv"  >
        <h1 class="heading">Over All Score</h1>
    <div class="circle" data-value="0.5">
        
    <div class="value"></div>
        </div>
        
        <div id="div1" >
            <div class="subdiv"><img class="myimg"src="Images/view.png"/></div>
            <div class="subdiv" ><img class="myimg" src="Images/share.png"/>
                
                
                </div>
            <div class="subdiv"><img class="myimg" src="Images/download.png"/></div>
</div>
</div>
    </body>
    </html>

**Comment by pourush77** [comment]
can u please show with an example ?
Here is my code :<script>
            $(document).ready(function(){
            var circle=$('.circle'),value=circle.children('.value');
                
                circle.circleProgress({startAngle:-190}).on('circle-animation-progress',function(e,p,v){
                    value.text((v*100).toFixed());
                    
                    
                });
                
        
            
          
                
            });
                 
        </script>

**Comment by pourush77** [comment]
<script>
            $(document).ready(function(){
            var circle=$('.circle'),value=circle.children('.value');
                
                circle.circleProgress({startAngle:-190}).on('circle-animation-progress',function(e,p,v){
                    value.text((v*100).toFixed());
                    
                    
                });
                
        
            
          
                
            });
                 
        </script>

**Comment by pourush77** [comment]
<script>
            $(document).ready(function(){
            var circle=$('.circle'),value=circle.children('.value');
                
                circle.circleProgress({startAngle:-190}).on('circle-animation-progress',function(e,p,v){
                    value.text((v*100).toFixed());
                    
                    
                });
                
        
            
          
                
            });
                 
        </script>

**Comment by pourush77** [comment]
![s1](https://cloud.githubusercontent.com/assets/19535093/15923409/b59d6d48-2e4a-11e6-87c9-e9604a4d95d1.PNG)

**Comment by kottenator** [comment]
One hint for you: when you want to post some code block on GitHub, [read the guide](https://guides.github.com/features/mastering-markdown/).

**Comment by kottenator** [comment]
Another hint, about my library: `el.circleProgress({startAngle: -190})` - the angle is in radians, not degrees, so if you want e.g. `90°` - write  `el.circleProgress({startAngle: Math.PI / 4})`

**Comment by kottenator** [comment]
And here is an example of updating value:

```js
var circle = $('.circle').circleProgress({value: 0.5});

setTimeout(function() {
  circle.circleProgress('value', 0.2);
}, 1000);
```

**Comment by kottenator** [comment]
[Here is another example for you](http://jsbin.com/ripaxit/2/edit?html,js,output), with textbox.
