### ISSUE TITLE
how to have this rendered by my React Component? 

### ISSUE THREAD

**Issue by meenupurplestar** [kottenator/jquery-circle-progress#99]
Can you please help with this? Is it possible to render this Jquery plugin by using the render method of component class? If yes, how would I do that ?

**Comment by kottenator** [comment]
I'm not sure what component do you mean, but in general - just put `el.circleProgress(...)` inside your component render method (or callback).

**Comment by meenupurplestar** [comment]
Thanks for the prompt reply. I am sorry for being vague. But this whole thing is very new to me. 
This is something I have been trying to do.  


    class CircularProgressView extends Component {
     render()
      {
        // to return the jquery plugin inside of that <div> tag
        return <div class={view}></div>

       }
    }

I hope you get the idea now. Thanks

**Comment by kottenator** [comment]
This is ReactJS, right? I don't have much experience with it, but [here is a snippet for you](http://jsbin.com/duvino/3/edit?html,js,output).

**Comment by kottenator** [comment]
And just in case, here is the JS code from it:

```js
class CircularProgressView extends React.Component {
  render() {
    return <div className="circle" ref="el" {...this.props}></div>;
  }
  
  componentDidMount() {
    $(this.refs.el).circleProgress();
  }
}

ReactDOM.render(
  <CircularProgressView data-value="0.7" data-size="300" data-fill='{"color": "#f77"}'/>,
  document.getElementById('container')
);
```

**Comment by meenupurplestar** [comment]
Yes, React JS. Awesome! Thats exactly what I was looking for. Thanks a lot :)

**Comment by meenupurplestar** [comment]
Sorry, I didnt know if i had to open a new issue or stick to the same thread.

    <CircularProgressView data-value="0.7" data-size="300" data-fill='{"color": "#f77"}'/>,
  document.getElementById('container')

When you pass in the value 0.7 , is there a way to get the number 70 displayed at the centre of the circle ? I saw an example that did that : 


    circle.on('circle-animation-progress', function(e, v) {
        var obj = $(this).data('circle-progress'),
        ctx = obj.ctx,
        s = obj.size,
        sv = (84).toFixed(), // ---> I didnt want to hardcode the value in here 
        fill = obj.fill
        ctx.font = s / 2.5 + "px sans-serif";
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.fillStyle = fill;
        ctx.fillText(sv, s / 2, s / 2);
        ctx.restore();
    });

However, I didnt want to hard code the value. I wanted it to take the value for the centre of the circle from the value I pass in from the React Component <CircularprogressView data-value="0.7"/>  and display that number . Is there a way to do this? 
Thanks for your help in advance.

**Comment by meenupurplestar** [comment]
Thanks, i got it figured out! :)
